/* ============================================================
   난다사주 — 사주 자점 카드 데이터
   - 78장 정통 타로 (메이저 22 + 마이너 56) × 정방향/역방향 = 156
   - 추후 카드 추가/수정 쉽게 하기 위해 평탄한 배열 구조 사용
   - 각 카드: id, num, name, nameEn, suit, orientation,
              art (시각 모티프 키), keyword, headline,
              core(핵심), love(연애), money(금전), work(일/사업), caution(조심)
   ============================================================ */

const ART_KEYS = ["traveler","wand","priestess","empress","emperor","temple","lovers","chariot","strength","lantern","wheel","scales","hanged","scythe","vessel","chain","tower","star","moon","sun","trumpet","wreath","wands","cups","swords","pentacles"];

const CARDS = [

/* ===================== MAJOR ARCANA — 정방향 ===================== */
{ id:"M00U", num:"0", name:"광대", nameEn:"The Fool", suit:"major", orientation:"upright", art:"traveler",
  keyword:"새로운 시작 · 자유 · 직관",
  headline:'오늘은 "<em>거침없이 발 내딛는 날</em>"입니다.',
  core:"오래 머뭇거리던 일이 있다면 오늘 가볍게 한 발 옮겨 보세요. 손해를 재느라 못 가던 길이 막상 가 보면 트여 있습니다.",
  love:"재지 말고 솔직하게 다가가세요. 첫 연락, 첫 표현이 의외로 잘 통하는 흐름입니다.",
  money:"작은 시도는 길합니다. 다만 큰 베팅은 다음을 기약하세요. 씨앗을 심는 자리입니다.",
  work:"안 해본 일에 마음이 끌린다면 좋은 신호. 너무 큰 그림보다 작은 한 걸음부터 시작하세요.",
  caution:"무모함은 금물. 자유와 무책임은 한 끗 차이라는 걸 잊지 마세요." },

{ id:"M01U", num:"I", name:"마법사", nameEn:"The Magician", suit:"major", orientation:"upright", art:"wand",
  keyword:"의지 · 실행력 · 집중",
  headline:'오늘은 "<em>가진 것으로 결과를 내는 날</em>"입니다.',
  core:"이미 손에 있는 자원이 답입니다. 새로 갖추려 들지 말고 가진 패를 끝까지 써 보세요.",
  love:"표현의 기술이 통합니다. 같은 말이라도 어떻게 건네느냐로 분위기가 달라집니다.",
  money:"기획·영업·중개 흐름이 좋습니다. 말로 풀어내는 일이 돈으로 이어집니다.",
  work:"집중하면 평소의 두 배가 나오는 날. 멀티태스킹은 오히려 손해입니다.",
  caution:"잔머리는 곧 들통납니다. 진심 없는 말솜씨는 오늘 가장 빠르게 무너집니다." },

{ id:"M02U", num:"II", name:"여사제", nameEn:"The High Priestess", suit:"major", orientation:"upright", art:"priestess",
  keyword:"직관 · 침묵 · 내면",
  headline:'오늘은 "<em>말보다 감이 맞는 날</em>"입니다.',
  core:"분석으로 풀리지 않던 문제가 직관으로 보입니다. 머리 굴리기 전에 마음의 첫 느낌을 적어 두세요.",
  love:"드러나지 않은 상대의 마음이 보이는 날. 서두르지 말고 조용히 곁을 지키세요.",
  money:"드러난 정보보다 숨은 정보가 더 큽니다. 떠도는 말은 흘리고 흐름을 읽으세요.",
  work:"섣불리 결정하지 마세요. 오늘은 자료 모으고 다듬는 자리가 더 잘 어울립니다.",
  caution:"비밀은 비밀로 두세요. 가벼운 입이 가장 큰 적이 되는 흐름입니다." },

{ id:"M03U", num:"III", name:"여황제", nameEn:"The Empress", suit:"major", orientation:"upright", art:"empress",
  keyword:"풍요 · 다정함 · 결실",
  headline:'오늘은 "<em>채워서 베푸는 날</em>"입니다.',
  core:"다정함이 오늘 가장 큰 자산입니다. 받으려 하기 전에 먼저 한 번 채워 주세요. 흐름이 돌아옵니다.",
  love:"사소한 챙김 한 번이 큰 인상을 남깁니다. 따뜻한 한마디가 분위기를 바꿉니다.",
  money:"오래 길러 온 일이 작은 열매를 맺습니다. 큰 한 방보다 꾸준한 흐름이 답입니다.",
  work:"동료와의 협업에서 좋은 결과가 나옵니다. 혼자 끌고 가지 말고 곁을 챙기세요.",
  caution:"과한 책임감은 번아웃이 됩니다. 챙기는 만큼 자신도 챙기세요." },

{ id:"M04U", num:"IV", name:"황제", nameEn:"The Emperor", suit:"major", orientation:"upright", art:"emperor",
  keyword:"질서 · 책임 · 결단",
  headline:'오늘은 "<em>중심을 잡는 사람이 이기는 날</em>"입니다.',
  core:"흔들리는 상황일수록 단단함이 돋보입니다. 결정해야 할 일이 있다면 미루지 마세요.",
  love:"흐릿한 태도는 오늘 가장 큰 약점. 마음은 따뜻하게, 태도는 분명하게.",
  money:"규모 있는 흐름을 다룰 수 있는 날. 계약·계획·예산은 오늘 잡아 두면 길합니다.",
  work:"리더 자리가 어울립니다. 책임을 회피하지 않고 마주설 때 권위가 생깁니다.",
  caution:"고집은 권위가 아닙니다. 다른 의견을 막는 순간 오늘의 운이 식습니다." },

{ id:"M05U", num:"V", name:"교황", nameEn:"The Hierophant", suit:"major", orientation:"upright", art:"temple",
  keyword:"전통 · 가르침 · 신뢰",
  headline:'오늘은 "<em>검증된 길이 안전한 날</em>"입니다.',
  core:"새 길보다 이미 닦인 길이 더 잘 맞는 흐름입니다. 어른·선배·전문가의 한마디가 약입니다.",
  love:"진지한 관계로 한 단계 깊어질 수 있는 자리. 양가 어른과 얽힌 인연도 길합니다.",
  money:"검증된 곳, 오래된 거래처가 안전합니다. 낯선 제안은 한 박자 늦춰 보세요.",
  work:"규정·매뉴얼을 다시 읽어 두세요. 정도(正道)로 가야 인정받는 날입니다.",
  caution:"형식만 따지면 답답해집니다. 본질은 사람과 신뢰라는 걸 잊지 마세요." },

{ id:"M06U", num:"VI", name:"연인", nameEn:"The Lovers", suit:"major", orientation:"upright", art:"lovers",
  keyword:"선택 · 조화 · 끌림",
  headline:'오늘은 "<em>마음을 따르는 결정이 옳은 날</em>"입니다.',
  core:"두 갈래 길에서 망설였다면 오늘은 마음이 끌리는 쪽이 맞습니다. 계산보다 진심이 답입니다.",
  love:"기다리던 신호가 옵니다. 머뭇거리지 말고 마음에 솔직해지세요.",
  money:"파트너십·동업·공동 투자에 길한 흐름. 단 계약은 분명히 해 두세요.",
  work:"가치 맞는 사람과 함께하면 평소의 두 배가 나오는 날입니다.",
  caution:"양다리·이중 의도는 오늘 가장 빠르게 들통납니다. 깨끗한 선택만 남기세요." },

{ id:"M07U", num:"VII", name:"전차", nameEn:"The Chariot", suit:"major", orientation:"upright", art:"chariot",
  keyword:"추진력 · 승리 · 의지",
  headline:'오늘은 "<em>밀어붙이는 사람이 가져가는 날</em>"입니다.',
  core:"속도가 곧 운입니다. 머뭇대지 말고 결심한 방향으로 단번에 가세요. 흐름이 등을 밀어 줍니다.",
  love:"먼저 다가가는 쪽이 분위기를 가져갑니다. 망설이면 다른 사람에게 자리를 내줍니다.",
  money:"진행 중인 건이 한 단계 진척되는 날. 결제·계약은 빠르게 마무리하세요.",
  work:"외부와의 협상·미팅에서 좋은 결과가 납니다. 자신감 있는 태도가 핵심입니다.",
  caution:"방향 없는 속도는 사고가 됩니다. 출발 전에 목적지를 다시 점검하세요." },

{ id:"M08U", num:"VIII", name:"힘", nameEn:"Strength", suit:"major", orientation:"upright", art:"strength",
  keyword:"용기 · 자제 · 부드러운 힘",
  headline:'오늘은 "<em>참는 사람이 이기는 날</em>"입니다.',
  core:"감정을 누르는 힘이 곧 실력이 되는 자리. 화내고 싶을 때 한 번 더 미소 짓는 사람이 결국 가져갑니다.",
  love:"상대의 서툰 표현을 너그럽게 받아 주세요. 다정한 인내가 깊은 신뢰로 돌아옵니다.",
  money:"조급한 손절·매수보다 흐름을 지켜보는 게 답. 인내가 곧 수익입니다.",
  work:"까다로운 사람과의 일에서 부드러운 태도가 통합니다. 강하게 누를수록 어긋납니다.",
  caution:"억지로 누르기만 하면 폭발합니다. 풀어 줄 곳은 풀어 주세요." },

{ id:"M09U", num:"IX", name:"은둔자", nameEn:"The Hermit", suit:"major", orientation:"upright", art:"lantern",
  keyword:"성찰 · 고요 · 내면의 등불",
  headline:'오늘은 "<em>혼자만의 시간이 약이 되는 날</em>"입니다.',
  core:"사람이 많을수록 흐려집니다. 잠시 떨어져 자기 안의 답을 들어 보세요. 조용한 곳에서 길이 보입니다.",
  love:"무리해서 다가가지 마세요. 잠시 거리를 두는 게 오히려 관계를 살립니다.",
  money:"무리한 확장은 보류. 가진 것을 정돈하는 자리가 더 어울립니다.",
  work:"몰입이 가능한 일에 시간을 몰아 주세요. 회의·잡무는 최대한 줄이는 게 좋습니다.",
  caution:"고립과 회피는 다릅니다. 피해야 할 결정을 미루는 핑계로 쓰지 마세요." },

{ id:"M10U", num:"X", name:"운명의 수레바퀴", nameEn:"Wheel of Fortune", suit:"major", orientation:"upright", art:"wheel",
  keyword:"전환 · 운의 흐름 · 기회",
  headline:'오늘은 "<em>흐름이 바뀌는 날</em>"입니다.',
  core:"정체되어 있던 일이 갑자기 풀릴 수 있습니다. 우연처럼 찾아오는 신호를 흘려보내지 마세요.",
  love:"오래 끊겼던 인연이나 새로운 만남이 들어올 수 있는 자리.",
  money:"막혔던 자금·결제가 풀리는 흐름. 행운은 준비된 손에만 잡힙니다.",
  work:"예상 밖의 제안·연락이 옵니다. 일단 듣고 빠르게 판단하세요.",
  caution:"운에만 기대지 마세요. 굴러가는 수레바퀴는 다음 한 칸엔 내려가기도 합니다." },

{ id:"M11U", num:"XI", name:"정의", nameEn:"Justice", suit:"major", orientation:"upright", art:"scales",
  keyword:"공정 · 균형 · 책임",
  headline:'오늘은 "<em>정직이 가장 큰 무기가 되는 날</em>"입니다.',
  core:"편법은 오늘 가장 빠르게 돌아옵니다. 분명한 원칙대로 가야 일이 매끄럽게 풀립니다.",
  love:"한쪽으로 기울어 있던 관계라면 오늘 균형을 잡아야 합니다. 솔직한 대화가 필요한 자리.",
  money:"정산·환급·세금 점검에 좋은 날. 미뤄둔 숫자를 오늘 마주하세요.",
  work:"계약서·합의서를 다시 읽어 보세요. 글자 하나가 흐름을 바꿀 수 있습니다.",
  caution:"감정으로 판단하면 손해입니다. 데이터를 보고 결정하세요." },

{ id:"M12U", num:"XII", name:"매달린 사람", nameEn:"The Hanged Man", suit:"major", orientation:"upright", art:"hanged",
  keyword:"전환의 시선 · 잠시 멈춤 · 희생",
  headline:'오늘은 "<em>한 발 물러서야 보이는 날</em>"입니다.',
  core:"같은 방식으로는 답이 없습니다. 한 박자 멈추고 시선을 뒤집어 보세요. 안 보이던 길이 보입니다.",
  love:"내 입장만 보던 시선을 상대 자리에 두는 순간 관계가 풀립니다.",
  money:"단기 손해를 감수해야 더 큰 흐름이 살아납니다. 매몰비용에 갇히지 마세요.",
  work:"잠시 보류가 답인 자리. 무리한 추진보다 호흡을 길게 가져가세요.",
  caution:"무작정 참는 건 희생이 아닙니다. 자기 자리를 잃는 인내는 그만하세요." },

{ id:"M13U", num:"XIII", name:"죽음", nameEn:"Death", suit:"major", orientation:"upright", art:"scythe",
  keyword:"마침 · 변화 · 다음 시작",
  headline:'오늘은 "<em>끝내야 다음이 열리는 날</em>"입니다.',
  core:"오래 끌어온 미련을 정리해야 새 흐름이 들어옵니다. 정리는 손해가 아니라 자리를 비우는 일입니다.",
  love:"맞지 않는 관계라면 오늘 매듭을 짓는 게 길합니다. 끝낸 자리에 새 인연이 들어옵니다.",
  money:"고질적인 지출 항목을 끊을 자리. 작은 결단이 한 달 흐름을 바꿉니다.",
  work:"안 풀리는 프로젝트는 과감히 접을 때. 다음 카드를 위해 자리를 비우세요.",
  caution:"파괴와 정리는 다릅니다. 충동적으로 다 엎지 말고 단계적으로 매듭지으세요." },

{ id:"M14U", num:"XIV", name:"절제", nameEn:"Temperance", suit:"major", orientation:"upright", art:"vessel",
  keyword:"조율 · 균형 · 인내의 흐름",
  headline:'오늘은 "<em>섞이는 사람이 이기는 날</em>"입니다.',
  core:"극단으로 가지 말고 중간을 만들어 보세요. 부드럽게 섞이는 태도가 오늘 가장 큰 힘이 됩니다.",
  love:"온도 차이가 컸다면 오늘 맞추기 좋습니다. 천천히, 자연스럽게 다가가세요.",
  money:"수입과 지출의 균형을 맞추는 자리. 한쪽이 무너져 있다면 오늘 손보세요.",
  work:"성격이 다른 팀과 일할 때 윤활유 역할이 잘 맞습니다. 중간에서 조율하는 사람이 빛납니다.",
  caution:"애매하게 두는 것과 조율하는 것은 다릅니다. 결정해야 할 건 정해 두세요." },

{ id:"M15U", num:"XV", name:"악마", nameEn:"The Devil", suit:"major", orientation:"upright", art:"chain",
  keyword:"집착 · 욕망 · 자기 함정",
  headline:'오늘은 "<em>붙잡고 있던 끈을 보는 날</em>"입니다.',
  core:"끊고 싶지만 못 끊던 습관·관계·욕망이 있다면 오늘 마주 보세요. 알면서 안 끊는 것이 가장 위험합니다.",
  love:"끌림은 강하지만 길이 보이지 않는 관계가 있다면 한 번 점검하세요.",
  money:"한 방을 노리는 마음, 달콤한 제안일수록 뒤를 보세요. 욕심이 가장 큰 함정입니다.",
  work:"성과에 집착할수록 일이 어그러집니다. 한 발 떨어져서 다시 보세요.",
  caution:"중독성 있는 자극을 줄이는 게 오늘의 첫걸음. 한 가지만이라도 멈춰 보세요." },

{ id:"M16U", num:"XVI", name:"탑", nameEn:"The Tower", suit:"major", orientation:"upright", art:"tower",
  keyword:"균열 · 충격 · 강제 정리",
  headline:'오늘은 "<em>무너진 자리가 자리를 비워 주는 날</em>"입니다.',
  core:"예상치 못한 변동이 있을 수 있습니다. 다만 무너지는 자리는 원래 약했던 자리. 충격이 오히려 정리를 도와줍니다.",
  love:"숨겨졌던 갈등이 터질 수 있습니다. 회피하지 말고 마주 보세요.",
  money:"돌발 지출에 대비. 안전 자금을 미리 확보해 두면 흔들리지 않습니다.",
  work:"기존 방식이 통하지 않는 신호가 옵니다. 빨리 인정하고 방향을 트세요.",
  caution:"충격을 핑계로 모든 걸 엎지 마세요. 무너진 자리만 정리하면 충분합니다." },

{ id:"M17U", num:"XVII", name:"별", nameEn:"The Star", suit:"major", orientation:"upright", art:"star",
  keyword:"희망 · 회복 · 영감",
  headline:'오늘은 "<em>다시 빛이 드는 날</em>"입니다.',
  core:"지쳐 있던 마음에 작은 빛이 들어옵니다. 포기하지 않은 사람에게만 돌아오는 흐름입니다.",
  love:"순수한 마음이 통합니다. 너무 재지 말고 솔직한 표현이 답입니다.",
  money:"끊겼던 기회·거래가 다시 살아날 수 있는 자리. 천천히, 그러나 분명하게.",
  work:"창의적인 아이디어가 떠오릅니다. 메모해 두세요. 작은 영감이 큰 흐름이 됩니다.",
  caution:"빛은 들어왔지만 아직 한낮은 아닙니다. 들뜨지 말고 한 걸음씩 가세요." },

{ id:"M18U", num:"XVIII", name:"달", nameEn:"The Moon", suit:"major", orientation:"upright", art:"moon",
  keyword:"불안 · 환상 · 무의식",
  headline:'오늘은 "<em>흐릿한 것을 확인하는 날</em>"입니다.',
  core:"감정이 일렁이기 쉽습니다. 확신이 없는 결정은 미루세요. 오늘은 보는 것보다 의심하는 게 안전합니다.",
  love:"상대의 말과 행동이 다르게 느껴진다면 직감이 맞을 가능성이 큽니다.",
  money:"좋아 보이는 제안일수록 작은 글씨까지 다 읽으세요. 오늘 흔들리면 길게 무립니다.",
  work:"불확실한 정보로 움직이지 마세요. 출처를 한 번 더 확인하는 자리.",
  caution:"두려움은 키울수록 커집니다. 사실과 상상을 분리해서 적어 보세요." },

{ id:"M19U", num:"XIX", name:"태양", nameEn:"The Sun", suit:"major", orientation:"upright", art:"sun",
  keyword:"성취 · 활력 · 밝음",
  headline:'오늘은 "<em>웃으면 풀리는 날</em>"입니다.',
  core:"막혀 있던 일이 한꺼번에 풀리는 흐름. 자신감 있게 움직이세요. 표정 하나로 분위기가 바뀝니다.",
  love:"솔직한 호감이 가장 큰 매력. 복잡하게 만들지 말고 밝게 표현하세요.",
  money:"수입·정산·계약 모두 좋은 소식이 따라옵니다. 다만 들떠서 큰돈을 쓰진 마세요.",
  work:"인정받는 자리. 그동안의 노력이 한 번에 결실을 보는 날입니다.",
  caution:"자만은 다음 카드를 어둡게 만듭니다. 받은 빛만큼 나눠 주세요." },

{ id:"M20U", num:"XX", name:"심판", nameEn:"Judgement", suit:"major", orientation:"upright", art:"trumpet",
  keyword:"부활 · 결산 · 부름",
  headline:'오늘은 "<em>지난 흐름을 결산하는 날</em>"입니다.',
  core:"지나온 길을 한 번 돌아볼 자리입니다. 이어 갈 건 이어 가고, 끝낼 건 끝내세요. 오늘의 매듭이 다음 주기를 결정합니다.",
  love:"한참 멀어졌던 인연이 다시 신호를 보낼 수 있는 자리.",
  money:"오래 끌던 정산·환급이 마무리됩니다. 미뤄둔 숫자를 오늘 마주하세요.",
  work:"과거의 노력이 평가받는 날. 양심에 솔직한 결정이 길게 갑니다.",
  caution:"자기 비난은 결산이 아닙니다. 잘한 부분을 먼저 인정해 주세요." },

{ id:"M21U", num:"XXI", name:"세계", nameEn:"The World", suit:"major", orientation:"upright", art:"wreath",
  keyword:"완성 · 통합 · 한 주기의 마무리",
  headline:'오늘은 "<em>한 매듭이 완성되는 날</em>"입니다.',
  core:"오래 끌어 온 일이 마무리되는 흐름. 작은 성과라도 분명히 챙기세요. 오늘의 매듭이 다음 큰 흐름의 기반이 됩니다.",
  love:"오래 만난 인연이라면 한 단계 깊어질 수 있는 자리. 결혼·동거 같은 결정도 길합니다.",
  money:"큰 흐름의 정리가 끝나는 자리. 다음 주기를 위한 계획을 시작해도 좋습니다.",
  work:"프로젝트의 완성·승진·이직 등 한 챕터가 마무리되는 날.",
  caution:"끝났다고 놓아 버리지 마세요. 다음 한 주기는 이미 시작되고 있습니다." },

/* ===================== MAJOR ARCANA — 역방향 ===================== */
{ id:"M00R", num:"0", name:"광대 (역)", nameEn:"The Fool · Reversed", suit:"major", orientation:"reversed", art:"traveler",
  keyword:"무모함 · 회피 · 미성숙",
  headline:'오늘은 "<em>가벼움이 가벼움으로 끝나는 날</em>"입니다.',
  core:"준비 없는 도전은 손해로 돌아옵니다. 오늘은 새 일보다 하던 일부터 매듭지으세요.",
  love:"무책임한 표현은 신뢰를 깎습니다. 가볍게 던진 말 한마디가 길게 남습니다.",
  money:"충동적인 결제·투자는 금물. 영수증을 한 번 더 살피세요.",
  work:"중요한 결정을 즉흥적으로 내리지 마세요. 자리에 무게가 빠지는 날입니다.",
  caution:"문제를 회피하는 자유는 자유가 아닙니다. 직면해야 끝납니다." },

{ id:"M01R", num:"I", name:"마법사 (역)", nameEn:"The Magician · Reversed", suit:"major", orientation:"reversed", art:"wand",
  keyword:"기만 · 잔재주 · 미완성",
  headline:'오늘은 "<em>잔머리가 들통나는 날</em>"입니다.',
  core:"숨겨두려 한 의도가 드러나기 쉬운 자리. 어설픈 포장보다 솔직한 인정이 빠릅니다.",
  love:"보여 주려는 마음이 앞서면 부담만 줍니다. 꾸미지 말고 그대로 가세요.",
  money:"확실치 않은 정보로 움직이지 마세요. 손해의 시작은 과신입니다.",
  work:"실력보다 말이 앞서면 신뢰가 깎입니다. 결과로 보여 줄 자리는 오늘이 아닙니다.",
  caution:"본인 능력의 한계를 인정하는 게 오늘의 첫 단추입니다." },

{ id:"M02R", num:"II", name:"여사제 (역)", nameEn:"The High Priestess · Reversed", suit:"major", orientation:"reversed", art:"priestess",
  keyword:"감정 과부하 · 비밀의 누설",
  headline:'오늘은 "<em>새어 나가기 쉬운 날</em>"입니다.',
  core:"감추던 마음·정보가 새기 쉬운 자리. 말을 줄이고 듣는 자리에 더 오래 머무세요.",
  love:"감정이 한 번에 터질 수 있습니다. 충동적인 고백·이별 통보는 한 박자 늦추세요.",
  money:"감으로 던지는 결정은 금물. 분석으로 보충해야 안전합니다.",
  work:"제3자에게 흘러간 정보가 부메랑이 됩니다. 누구에게 어디까지 말했는지 점검하세요.",
  caution:"마음 정리가 안 되어 있을수록 다른 사람을 끌어들이지 마세요." },

{ id:"M03R", num:"III", name:"여황제 (역)", nameEn:"The Empress · Reversed", suit:"major", orientation:"reversed", art:"empress",
  keyword:"공허 · 과보호 · 미숙한 풍요",
  headline:'오늘은 "<em>퍼주기만 하면 비는 날</em>"입니다.',
  core:"너무 챙기느라 자신이 비고 있지 않은지 보세요. 거절도 다정함의 한 부분입니다.",
  love:"애정이 일방적이라면 오늘 한 번 돌아볼 자리.",
  money:"기분 따라 쓰는 소비는 후회가 길게 갑니다. 카드 한도부터 점검하세요.",
  work:"책임을 다 떠안다 보면 결과가 오히려 흐려집니다. 분배가 필요한 자리.",
  caution:"감정으로 가족·연인에게 휘둘리지 않게 거리를 두세요." },

{ id:"M04R", num:"IV", name:"황제 (역)", nameEn:"The Emperor · Reversed", suit:"major", orientation:"reversed", art:"emperor",
  keyword:"독선 · 강압 · 권위 남용",
  headline:'오늘은 "<em>고집이 길을 막는 날</em>"입니다.',
  core:"내 방식이 늘 맞는다는 확신이 가장 큰 적입니다. 다른 의견을 한 번만 끝까지 들어 보세요.",
  love:"통제하려는 태도는 거리감만 키웁니다. 부드러운 표현으로 바꾸세요.",
  money:"무리한 확장·과한 자신감은 손실로 이어집니다. 보수적으로 가세요.",
  work:"부하·동료의 반발이 보이면 이미 늦은 신호. 권위가 아니라 신뢰로 풀어야 합니다.",
  caution:"분노로 내린 결정은 거의 후회로 돌아옵니다. 한 박자 늦추세요." },

{ id:"M05R", num:"V", name:"교황 (역)", nameEn:"The Hierophant · Reversed", suit:"major", orientation:"reversed", art:"temple",
  keyword:"형식주의 · 위선 · 답답함",
  headline:'오늘은 "<em>틀을 깨야 풀리는 날</em>"입니다.',
  core:"관습대로만 가다 보면 길이 막힙니다. 오늘은 본질만 남기고 형식은 가볍게 보세요.",
  love:"체면·남의 시선 때문에 마음이 막혀 있다면 오늘 한 번 정리하세요.",
  money:"오래된 관행을 그대로 따르다가는 손해. 새 구조를 검토할 자리입니다.",
  work:"매뉴얼 너머에 답이 있는 날. 실험이 필요한 자리입니다.",
  caution:"규칙을 깨자는 핑계로 무책임해지진 마세요. 책임은 늘 본인 몫." },

{ id:"M06R", num:"VI", name:"연인 (역)", nameEn:"The Lovers · Reversed", suit:"major", orientation:"reversed", art:"lovers",
  keyword:"부조화 · 흔들림 · 잘못된 선택",
  headline:'오늘은 "<em>흐림이 흐림을 부르는 날</em>"입니다.',
  core:"두 갈래에서 우왕좌왕하면 둘 다 잃습니다. 오늘은 한쪽으로 분명히 기울어 두세요.",
  love:"양다리·미련·삼각 흐름은 오늘 가장 빠르게 터집니다. 솔직한 정리가 답.",
  money:"공동 명의·동업에 잡음이 생길 수 있는 자리. 계약서 다시 읽으세요.",
  work:"가치가 맞지 않는 협업은 오늘 어긋납니다. 무리해서 끌고 가지 마세요.",
  caution:"마음이 흔들릴수록 큰 결정은 다음으로 미루세요." },

{ id:"M07R", num:"VII", name:"전차 (역)", nameEn:"The Chariot · Reversed", suit:"major", orientation:"reversed", art:"chariot",
  keyword:"통제 상실 · 방향 잃음 · 과속",
  headline:'오늘은 "<em>고삐가 빠지기 쉬운 날</em>"입니다.',
  core:"속도가 빨라질수록 방향이 흐려지기 쉬운 자리. 출발 전에 목적지를 한 번 더 점검하세요.",
  love:"감정을 무리해서 밀어붙이면 역효과. 잠시 거리를 두세요.",
  money:"성급한 매수·매도는 손실. 데이터를 다시 한 번 보세요.",
  work:"마감에 쫓겨 무리하면 실수가 큽니다. 우선순위를 정해 자르고 가세요.",
  caution:"피로 상태에서의 운전·이동은 조심. 작은 사고가 큰 일로 이어질 수 있습니다." },

{ id:"M08R", num:"VIII", name:"힘 (역)", nameEn:"Strength · Reversed", suit:"major", orientation:"reversed", art:"strength",
  keyword:"불안 · 자기 의심 · 폭발",
  headline:'오늘은 "<em>참기만 하다 터지기 쉬운 날</em>"입니다.',
  core:"억지로 누르고 있던 감정이 한 번에 터질 수 있습니다. 새는 곳을 적당히 풀어 주세요.",
  love:"상대에게 화나는 지점이 있다면 차분하게 한 번 말해 두는 게 길합니다.",
  money:"불안 매도·충동 손절은 후회 큰 자리. 한 박자 늦추세요.",
  work:"자신감이 떨어질 때일수록 잘하는 일에 집중하세요.",
  caution:"자기 비난은 절제가 아닙니다. 자신에게 부드러워질 줄도 알아야 합니다." },

{ id:"M09R", num:"IX", name:"은둔자 (역)", nameEn:"The Hermit · Reversed", suit:"major", orientation:"reversed", art:"lantern",
  keyword:"고립 · 회피 · 외로움",
  headline:'오늘은 "<em>혼자 있는 게 답이 아닌 날</em>"입니다.',
  core:"너무 오래 닫고 있던 마음이 있다면 오늘은 한 사람에게라도 말을 꺼내 보세요.",
  love:"거리감을 만들수록 상대도 멀어집니다. 작은 안부 한마디로 충분합니다.",
  money:"혼자만의 판단이 위험한 자리. 신뢰할 만한 사람의 의견을 한 번 들어 보세요.",
  work:"잠수 타고 미루면 일이 더 커집니다. 어렵게 입을 떼는 게 빠른 길.",
  caution:"외로움을 자존심으로 덮지 마세요. 감정은 인정해야 흘러갑니다." },

{ id:"M10R", num:"X", name:"운명의 수레바퀴 (역)", nameEn:"Wheel of Fortune · Reversed", suit:"major", orientation:"reversed", art:"wheel",
  keyword:"하강 · 정체 · 운에 의존",
  headline:'오늘은 "<em>흐름이 무거운 날</em>"입니다.',
  core:"운에만 기대면 어긋납니다. 오늘은 손에 잡히는 일부터 하나씩 처리하세요.",
  love:"기다리는 연락만 보지 말고 다른 흐름에도 마음을 두세요.",
  money:"막연한 기대 투자보다 현금 흐름 점검이 우선.",
  work:"진행 중인 일이 한 박자 늦어질 수 있습니다. 데드라인을 보수적으로 잡으세요.",
  caution:"점·운세에 의지가 기울 수 있는 날. 결정의 책임은 결국 본인 몫입니다." },

{ id:"M11R", num:"XI", name:"정의 (역)", nameEn:"Justice · Reversed", suit:"major", orientation:"reversed", art:"scales",
  keyword:"불공정 · 회피 · 책임 전가",
  headline:'오늘은 "<em>균형이 한쪽으로 기우는 날</em>"입니다.',
  core:"한쪽만 손해 보는 구조라면 오늘 짚어야 합니다. 묻어두면 더 커집니다.",
  love:"같은 갈등이 반복된다면 진짜 이유를 회피하고 있는 건 아닌지 보세요.",
  money:"미루던 세금·정산·환급 건이 부메랑이 될 수 있습니다.",
  work:"책임 떠넘기기, 평가의 불공정에 휘둘리지 마세요. 기록을 남겨 두세요.",
  caution:"화를 정의로 포장하지 마세요. 감정이 앞서면 판단이 흐려집니다." },

{ id:"M12R", num:"XII", name:"매달린 사람 (역)", nameEn:"The Hanged Man · Reversed", suit:"major", orientation:"reversed", art:"hanged",
  keyword:"정체 · 무의미한 인내 · 미적거림",
  headline:'오늘은 "<em>버티기만 해선 안 되는 날</em>"입니다.',
  core:"답이 안 보이는 자리에 너무 오래 머무르고 있지 않은지 보세요. 멈춤도 끝이 있어야 합니다.",
  love:"같은 갈등을 묻어두면 점점 무거워집니다. 짧게라도 짚고 가세요.",
  money:"잃은 자리를 회복하려고 더 묶어 두면 손해가 커집니다.",
  work:"방향이 안 맞는 일을 의리로만 끌고 가지 마세요.",
  caution:"희생이 길어지면 분노가 됩니다. 자기 자리를 지키는 것도 책임입니다." },

{ id:"M13R", num:"XIII", name:"죽음 (역)", nameEn:"Death · Reversed", suit:"major", orientation:"reversed", art:"scythe",
  keyword:"미련 · 변화 거부 · 지연된 마무리",
  headline:'오늘은 "<em>못 놓는 자리가 발목 잡는 날</em>"입니다.',
  core:"끝났음을 알면서도 붙잡고 있는 게 있다면 오늘 한 매듭만이라도 지으세요.",
  love:"옛 인연에 다시 흔들릴 수 있는 자리. 같은 결말을 반복하지 마세요.",
  money:"손절해야 할 자리를 미루면 손실이 더 커집니다.",
  work:"오래된 방식·도구·관계를 점검할 자리. 한 번에 못 바꾸면 한 가지부터.",
  caution:"변화에 대한 두려움이 가장 큰 적입니다." },

{ id:"M14R", num:"XIV", name:"절제 (역)", nameEn:"Temperance · Reversed", suit:"major", orientation:"reversed", art:"vessel",
  keyword:"불균형 · 과도함 · 어긋남",
  headline:'오늘은 "<em>한쪽으로 쏠리면 무너지는 날</em>"입니다.',
  core:"일·관계·소비 중 한쪽이 과해진 자리. 오늘 점검하지 않으면 다음 주에 표가 납니다.",
  love:"한 사람만의 양보·노력으로 유지된 관계라면 오늘 짚어야 합니다.",
  money:"과한 지출·과한 절약 둘 다 흐름을 깨뜨립니다. 중간을 잡으세요.",
  work:"무리한 일정은 결국 품질을 떨어뜨립니다. 작업량을 다시 배분하세요.",
  caution:"술·음식·자극의 과한 섭취 주의. 몸이 가장 빨리 표를 냅니다." },

{ id:"M15R", num:"XV", name:"악마 (역)", nameEn:"The Devil · Reversed", suit:"major", orientation:"reversed", art:"chain",
  keyword:"해방 · 끊어냄 · 자각",
  headline:'오늘은 "<em>사슬 한 칸을 끊는 날</em>"입니다.',
  core:"붙잡고 있던 습관·관계·생각에서 한 칸이라도 풀려나는 흐름. 작은 결단이 큰 자유로 이어집니다.",
  love:"끌림만으로 유지된 관계의 정체가 보이는 자리. 정리할 자리는 정리하세요.",
  money:"불필요한 구독·자동결제·도박성 지출을 끊을 자리.",
  work:"독성 있는 관계·환경에서 한 발 떨어지는 게 답.",
  caution:"중독에서 빠져나오는 첫날일수록 흔들리기 쉽습니다. 한 사람의 지지가 큰 힘이 됩니다." },

{ id:"M16R", num:"XVI", name:"탑 (역)", nameEn:"The Tower · Reversed", suit:"major", orientation:"reversed", art:"tower",
  keyword:"지연된 붕괴 · 변화 회피",
  headline:'오늘은 "<em>균열을 직시해야 하는 날</em>"입니다.',
  core:"이미 금이 가 있는 구조를 외면해 왔다면 오늘 들여다보세요. 무너지기 전에 손볼 자리가 보입니다.",
  love:"덮어두던 갈등을 짧게라도 짚어 두세요. 미루면 한꺼번에 옵니다.",
  money:"숨겨둔 부채·연체를 마주할 자리. 작은 직면이 큰 손실을 막습니다.",
  work:"비효율 구조를 끌고 가던 부서·시스템이 있다면 점검을 시작하세요.",
  caution:"무너지는 두려움보다 모른 척하는 비용이 더 큽니다." },

{ id:"M17R", num:"XVII", name:"별 (역)", nameEn:"The Star · Reversed", suit:"major", orientation:"reversed", art:"star",
  keyword:"낙담 · 신념의 흔들림",
  headline:'오늘은 "<em>희망이 흐릿하게 느껴지는 날</em>"입니다.',
  core:"포기하고 싶은 마음이 들 수 있는 자리. 다만 흐릿한 빛도 빛입니다. 오늘은 결과보다 회복에 시간을 두세요.",
  love:"기대를 너무 키우지 마세요. 작은 만남이라도 의미를 가볍게 두는 게 편합니다.",
  money:"단기 결과에 일희일비하지 마세요. 흐름은 긴 호흡으로 봐야 합니다.",
  work:"자신감이 떨어질 수 있는 자리. 잘했던 결과물 하나를 다시 꺼내 보세요.",
  caution:"비교는 오늘 가장 큰 독입니다. SNS·뉴스 한 박자 줄이세요." },

{ id:"M18R", num:"XVIII", name:"달 (역)", nameEn:"The Moon · Reversed", suit:"major", orientation:"reversed", art:"moon",
  keyword:"진실의 드러남 · 혼란의 해소",
  headline:'오늘은 "<em>안개가 걷히는 날</em>"입니다.',
  core:"오래 흐릿했던 부분이 정리되는 흐름. 다만 드러난 진실을 마주할 용기는 필요합니다.",
  love:"의심하던 부분이 사실로 확인될 수 있는 자리. 차분하게 다음을 정하세요.",
  money:"숨겨졌던 비용·구조가 보입니다. 정리할 기회로 삼으세요.",
  work:"오해가 풀리는 자리. 굳이 변명 길게 하지 말고 사실만 짧게 말하세요.",
  caution:"진실이 보였다고 즉시 큰 결정을 내리지 마세요. 한 박자 뒤가 안전합니다." },

{ id:"M19R", num:"XIX", name:"태양 (역)", nameEn:"The Sun · Reversed", suit:"major", orientation:"reversed", art:"sun",
  keyword:"기력 저하 · 과시 · 잠시의 흐림",
  headline:'오늘은 "<em>가벼운 구름이 잠시 지나는 날</em>"입니다.',
  core:"기운이 한 박자 떨어질 수 있지만 큰 흐름은 여전히 좋은 자리. 무리하지 말고 페이스 조절하세요.",
  love:"억지 미소보다 솔직한 표정이 답입니다.",
  money:"보여 주려는 지출은 후회로 돌아옵니다. 진짜 필요한 곳에만 쓰세요.",
  work:"성과 자랑보다 결과로 보여 줄 자리. 말은 줄이고 결과만 남기세요.",
  caution:"과한 자신감은 작은 사고로 이어집니다. 점검 한 번 더." },

{ id:"M20R", num:"XX", name:"심판 (역)", nameEn:"Judgement · Reversed", suit:"major", orientation:"reversed", art:"trumpet",
  keyword:"자기 비난 · 회피 · 같은 실수 반복",
  headline:'오늘은 "<em>같은 자리를 반복하기 쉬운 날</em>"입니다.',
  core:"비슷한 결과가 반복된다면 원인을 다른 곳에서 찾고 있는지 보세요. 답은 보통 가장 가까운 곳에 있습니다.",
  love:"같은 패턴의 이별·갈등을 반복하지 않으려면 짧은 노트라도 남겨 두세요.",
  money:"같은 항목에서 새는 돈이 없는지 점검하세요.",
  work:"피드백을 받을 자리. 방어하지 말고 들어 두세요.",
  caution:"자기 비난은 변화가 아닙니다. 한 가지 행동을 바꾸는 게 시작입니다." },

{ id:"M21R", num:"XXI", name:"세계 (역)", nameEn:"The World · Reversed", suit:"major", orientation:"reversed", art:"wreath",
  keyword:"미완성 · 마지막 한 끗 · 지연",
  headline:'오늘은 "<em>마지막 매듭이 안 묶이기 쉬운 날</em>"입니다.',
  core:"거의 다 왔는데 한 끗이 부족한 자리. 끝까지 챙겨야 결실이 됩니다. 마지막 점검에 시간을 들이세요.",
  love:"결정만 남은 자리라면 오늘 분명히 짚어 두세요. 미루면 흐름이 다시 식습니다.",
  money:"미수금·정산 건 마무리에 집중. 다음 주기로 끌고 가면 비용이 커집니다.",
  work:"프로젝트 마감 단계의 작은 누락을 챙기세요. 마지막 1%가 평판을 만듭니다.",
  caution:"이만하면 됐다는 마음이 가장 큰 적입니다." },

/* ===================== WANDS (지팡이 · 불) ===================== */
{ id:"W01U", num:"Ace", name:"지팡이 에이스", nameEn:"Ace of Wands", suit:"wands", orientation:"upright", art:"wands",
  keyword:"불꽃 같은 시작 · 영감",
  headline:'오늘은 "<em>의욕이 살아나는 날</em>"입니다.',
  core:"새로 시작하고 싶은 마음이 강하게 오는 자리. 그 첫 불꽃을 행동으로 옮기세요.",
  love:"호감이 생긴다면 망설이지 말고 신호를 보내세요.",
  money:"새 수입 통로의 가능성이 열리는 자리. 메모해 두세요.",
  work:"새 프로젝트·기획을 띄우기 좋은 날. 빠른 착수가 답.",
  caution:"불꽃은 빨리 식기도 합니다. 시작 다음의 두 번째 발을 미리 정해 두세요." },

{ id:"W02U", num:"2", name:"지팡이 2", nameEn:"Two of Wands", suit:"wands", orientation:"upright", art:"wands",
  keyword:"계획 · 선택 · 확장",
  headline:'오늘은 "<em>큰 그림을 그리는 날</em>"입니다.',
  core:"한 단계 위에서 흐름을 보세요. 좁은 시야를 넓히면 새 길이 보입니다.",
  love:"장기적인 그림을 같이 그릴 수 있는 사람인지 점검하기 좋은 자리.",
  money:"중장기 자산 배분을 다시 짤 자리.",
  work:"진로·이직·확장 계획을 검토할 자리. 결정 전에 자료를 모으세요.",
  caution:"그림만 그리다 출발을 놓치지 마세요." },

{ id:"W03U", num:"3", name:"지팡이 3", nameEn:"Three of Wands", suit:"wands", orientation:"upright", art:"wands",
  keyword:"확장 · 기다림 · 멀리 보기",
  headline:'오늘은 "<em>심어 둔 자리를 지켜보는 날</em>"입니다.',
  core:"이미 시작해 둔 일이 결과로 돌아오는 흐름. 조급해하지 말고 기다리세요.",
  love:"먼 거리·외부 환경의 인연이 들어올 수 있는 자리.",
  money:"해외·외부와 연결된 수입 흐름이 길합니다.",
  work:"외부 협력·미팅·확장 검토에 좋은 자리.",
  caution:"기다림과 방치는 다릅니다. 점검은 계속하세요." },

{ id:"W04U", num:"4", name:"지팡이 4", nameEn:"Four of Wands", suit:"wands", orientation:"upright", art:"wands",
  keyword:"축하 · 안정 · 기쁜 자리",
  headline:'오늘은 "<em>작은 결실을 함께 나누는 날</em>"입니다.',
  core:"한 매듭이 즐겁게 마무리되는 자리. 혼자 누리지 말고 곁의 사람과 나누세요.",
  love:"가족·친구 모임에서 좋은 인연이 들어올 수 있는 자리.",
  money:"보너스·정산·이벤트성 수입이 따라오는 흐름.",
  work:"팀의 작은 성과를 챙길 자리. 격려가 다음 한 달을 결정합니다.",
  caution:"흥에 들떠 큰 지출하지 마세요." },

{ id:"W05U", num:"5", name:"지팡이 5", nameEn:"Five of Wands", suit:"wands", orientation:"upright", art:"wands",
  keyword:"경쟁 · 충돌 · 시끌함",
  headline:'오늘은 "<em>의견이 부딪히기 쉬운 날</em>"입니다.',
  core:"각자 다른 방향으로 가는 흐름. 다툼처럼 보이지만 결국 더 나은 답이 나오는 자리입니다.",
  love:"사소한 말다툼은 약. 솔직하게 풀면 가까워집니다.",
  money:"경쟁 입찰·비교 견적에 좋은 자리.",
  work:"회의가 길어질 수 있습니다. 안건을 먼저 정리해 두세요.",
  caution:"감정이 앞서면 답이 안 나옵니다. 사실만 짧게." },

{ id:"W06U", num:"6", name:"지팡이 6", nameEn:"Six of Wands", suit:"wands", orientation:"upright", art:"wands",
  keyword:"승리 · 인정 · 외부 평가",
  headline:'오늘은 "<em>인정받는 날</em>"입니다.',
  core:"그동안의 노력이 외부 평가로 돌아오는 자리. 들떠도 좋지만 다음 카드를 준비하세요.",
  love:"호감이 자연스럽게 모이는 자리. 자신감 있게 다가가세요.",
  money:"성과급·외부 수익이 따라오는 흐름.",
  work:"발표·제안에서 좋은 결과. 자료보다 표정·태도가 더 큽니다.",
  caution:"자만하면 다음 카드가 어둡습니다." },

{ id:"W07U", num:"7", name:"지팡이 7", nameEn:"Seven of Wands", suit:"wands", orientation:"upright", art:"wands",
  keyword:"방어 · 자기 자리 지키기",
  headline:'오늘은 "<em>물러서지 말아야 하는 날</em>"입니다.',
  core:"외부에서 흔드는 흐름이 있어도 본인 자리만 단단히 지키면 결국 이깁니다.",
  love:"휘둘리지 말고 본인 기준을 먼저 챙기세요.",
  money:"본인 자산을 지키는 자리. 새 투자보다 방어가 먼저.",
  work:"본인 영역에 대한 외부 간섭은 분명히 선을 그으세요.",
  caution:"방어가 과해지면 적이 늘어납니다. 필요한 곳만." },

{ id:"W08U", num:"8", name:"지팡이 8", nameEn:"Eight of Wands", suit:"wands", orientation:"upright", art:"wands",
  keyword:"속도 · 빠른 진행 · 소식",
  headline:'오늘은 "<em>한꺼번에 풀리는 날</em>"입니다.',
  core:"막혀 있던 일들이 빠르게 돌아가는 자리. 들어오는 신호를 놓치지 마세요.",
  love:"기다리던 연락·답이 오는 자리. 빠르게 응답하세요.",
  money:"결제·입금이 빠르게 처리되는 흐름.",
  work:"이메일·연락이 폭주할 수 있습니다. 우선순위만 정해 두세요.",
  caution:"빠른 만큼 실수도 쉬워집니다. 보내기 전에 한 번만 더." },

{ id:"W09U", num:"9", name:"지팡이 9", nameEn:"Nine of Wands", suit:"wands", orientation:"upright", art:"wands",
  keyword:"끈기 · 마지막 한 걸음",
  headline:'오늘은 "<em>마지막 한 발이 남은 날</em>"입니다.',
  core:"지쳤지만 거의 다 온 자리. 여기서 멈추면 가장 아깝습니다.",
  love:"오래 끌어 온 갈등의 마지막 정리만 남은 자리.",
  money:"버티는 자리. 새 진입보다 마무리 먼저.",
  work:"마감 직전, 마지막 점검에 집중하세요.",
  caution:"방어적인 태도가 너무 굳어지지 않게 한 번 풀어 주세요." },

{ id:"W10U", num:"10", name:"지팡이 10", nameEn:"Ten of Wands", suit:"wands", orientation:"upright", art:"wands",
  keyword:"부담 · 책임 과다",
  headline:'오늘은 "<em>짐을 줄이는 날</em>"입니다.',
  core:"혼자 다 떠안고 있는 짐을 줄여야 다음이 보입니다. 한 가지만 내려놓아도 됩니다.",
  love:"감정 노동이 과한 관계라면 점검할 자리.",
  money:"미뤄둔 부담스러운 정산을 짧게라도 처리하세요.",
  work:"위임이 답인 자리. 다 할 수 있다는 마음이 가장 큰 짐입니다.",
  caution:"몸이 신호를 보내고 있는 자리. 무시하면 큽니다." },

{ id:"WPU", num:"Page", name:"지팡이 페이지", nameEn:"Page of Wands", suit:"wands", orientation:"upright", art:"wands",
  keyword:"새 영감 · 호기심 · 도전",
  headline:'오늘은 "<em>새로 배우는 자리가 어울리는 날</em>"입니다.',
  core:"호기심을 따라가는 게 곧 운입니다. 안 해본 것을 한 가지만 시도해 보세요.",
  love:"가벼운 시작이 좋습니다. 가볍게 다가가도 부담스럽지 않은 자리.",
  money:"새 부수입의 단서가 보이는 자리. 일단 메모.",
  work:"새 기술·새 사람·새 자리에 적응하기 좋은 흐름.",
  caution:"시작만 즐기지 마세요. 다음 한 걸음을 정해 두세요." },

{ id:"WKnU", num:"Knight", name:"지팡이 기사", nameEn:"Knight of Wands", suit:"wands", orientation:"upright", art:"wands",
  keyword:"열정 · 추진 · 모험",
  headline:'오늘은 "<em>밀어붙이면 가는 날</em>"입니다.',
  core:"속도가 핵심. 망설이는 사이 다른 사람이 가져갑니다.",
  love:"확실한 표현이 가장 빠릅니다.",
  money:"단기 흐름에 빠르게 올라타기 좋은 자리.",
  work:"외부 영업·미팅에 길합니다.",
  caution:"성급함은 사고를 부릅니다. 안전 점검 한 번 더." },

{ id:"WQU", num:"Queen", name:"지팡이 여왕", nameEn:"Queen of Wands", suit:"wands", orientation:"upright", art:"wands",
  keyword:"자신감 · 매력 · 카리스마",
  headline:'오늘은 "<em>당당함이 매력이 되는 날</em>"입니다.',
  core:"눈치 보지 마세요. 본인의 색깔을 분명히 드러낼수록 사람이 모입니다.",
  love:"먼저 다가가는 쪽이 분위기를 가져가는 자리.",
  money:"브랜드·이미지·콘텐츠 수익에 길한 흐름.",
  work:"발표·리더 역할에 잘 맞는 자리.",
  caution:"자신감과 자만은 다릅니다. 곁을 챙기는 한마디 잊지 마세요." },

{ id:"WKU", num:"King", name:"지팡이 왕", nameEn:"King of Wands", suit:"wands", orientation:"upright", art:"wands",
  keyword:"비전 · 통솔 · 결단",
  headline:'오늘은 "<em>방향을 정하는 사람이 되는 날</em>"입니다.',
  core:"흐릿한 그림 대신 분명한 방향을 제시할 자리. 결정한 다음엔 흔들리지 마세요.",
  love:"미래의 그림을 같이 그릴 수 있는 인연인지 점검할 자리.",
  money:"큰 그림의 자산 배분을 다시 짜기 좋은 흐름.",
  work:"리더로서의 결단이 필요한 자리. 망설이는 모습이 가장 큰 약점.",
  caution:"독단으로 흐르지 않게 한 사람의 의견은 반드시 들어 두세요." },

/* ===================== CUPS (컵 · 물) ===================== */
{ id:"C01U", num:"Ace", name:"컵 에이스", nameEn:"Ace of Cups", suit:"cups", orientation:"upright", art:"cups",
  keyword:"감정의 시작 · 사랑 · 영감",
  headline:'오늘은 "<em>마음이 열리는 날</em>"입니다.',
  core:"닫혀 있던 감정이 부드럽게 풀리는 자리. 솔직한 표현이 가장 큰 운입니다.",
  love:"새 인연의 신호가 들어오는 자리. 마음을 너무 재지 마세요.",
  money:"기쁜 소식이 작은 수입으로도 이어질 수 있는 흐름.",
  work:"창의력·표현·서비스 분야에서 좋은 결과가 나옵니다.",
  caution:"감정에 너무 휩쓸리면 결정이 흐려집니다." },

{ id:"C02U", num:"2", name:"컵 2", nameEn:"Two of Cups", suit:"cups", orientation:"upright", art:"cups",
  keyword:"연결 · 파트너십 · 균형",
  headline:'오늘은 "<em>마음이 통하는 사람을 만나는 날</em>"입니다.',
  core:"서로 다른 사람과의 의외의 케미가 생기는 자리. 솔직하게 다가가세요.",
  love:"가벼운 만남이 깊어질 수 있는 자리.",
  money:"동업·공동 작업에 길한 흐름.",
  work:"새 협업이 잘 풀립니다.",
  caution:"한쪽으로 기울면 균형이 깨집니다. 처음부터 분명히." },

{ id:"C03U", num:"3", name:"컵 3", nameEn:"Three of Cups", suit:"cups", orientation:"upright", art:"cups",
  keyword:"축하 · 우정 · 즐거운 자리",
  headline:'오늘은 "<em>좋은 자리에 함께하는 날</em>"입니다.',
  core:"오랜만의 모임·축하 자리가 길합니다. 사람 사이에서 좋은 흐름이 옵니다.",
  love:"친구 모임에서 새 인연이 들어오는 자리.",
  money:"공동 자축·작은 사치는 길. 다만 한도는 정해 두세요.",
  work:"팀의 결속이 강해지는 자리. 좋은 분위기가 곧 성과로 이어집니다.",
  caution:"분위기에 휩쓸려 약속 남발 주의." },

{ id:"C04U", num:"4", name:"컵 4", nameEn:"Four of Cups", suit:"cups", orientation:"upright", art:"cups",
  keyword:"권태 · 무관심 · 깊이 보기",
  headline:'오늘은 "<em>익숙함을 다시 보는 날</em>"입니다.',
  core:"늘 있던 자리가 시시하게 느껴진다면 시선을 살짝 바꿔 보세요. 익숙함 안에 답이 있습니다.",
  love:"오래된 인연의 새로운 매력이 보이는 자리.",
  money:"가진 자산을 다시 점검할 자리. 안 쓰는 자원이 더 클 수 있습니다.",
  work:"같은 일이 지겹다면 방식만 바꿔도 흐름이 달라집니다.",
  caution:"무기력에 머무르지 마세요. 한 가지만 움직여도 충분합니다." },

{ id:"C05U", num:"5", name:"컵 5", nameEn:"Five of Cups", suit:"cups", orientation:"upright", art:"cups",
  keyword:"상실 · 후회 · 남아 있는 것",
  headline:'오늘은 "<em>잃은 것보다 남은 것을 보는 날</em>"입니다.',
  core:"잃은 자리에 시선이 가도 남아 있는 자리를 잊지 마세요. 다음 흐름은 거기서 시작합니다.",
  love:"지난 인연의 미련을 정리할 자리.",
  money:"손실에 매몰되지 말고 회복 가능한 자리부터 챙기세요.",
  work:"실패한 프로젝트에서 배운 것을 메모해 두세요.",
  caution:"자기 비난이 가장 큰 손실입니다." },

{ id:"C06U", num:"6", name:"컵 6", nameEn:"Six of Cups", suit:"cups", orientation:"upright", art:"cups",
  keyword:"추억 · 향수 · 옛 인연",
  headline:'오늘은 "<em>옛 인연이 도움이 되는 날</em>"입니다.',
  core:"오래된 사람·자리에서 좋은 흐름이 옵니다. 연락이 끊겼던 인연을 챙겨 보세요.",
  love:"옛 인연이 다시 신호를 보낼 수 있는 자리. 다만 같은 결말이라면 반복은 의미 없습니다.",
  money:"오래 묵혀둔 자산에서 작은 수익이 따라올 수 있는 자리.",
  work:"과거 거래처·동료의 도움이 의외로 큽니다.",
  caution:"추억은 추억으로 두세요. 현실의 결정과 섞지 마세요." },

{ id:"C07U", num:"7", name:"컵 7", nameEn:"Seven of Cups", suit:"cups", orientation:"upright", art:"cups",
  keyword:"환상 · 선택지 · 흐릿함",
  headline:'오늘은 "<em>너무 많은 선택지 앞에 선 날</em>"입니다.',
  core:"가능성을 다 잡으려 하면 다 놓칩니다. 가장 현실적인 한 가지를 먼저 추리세요.",
  love:"이상형의 그림을 살짝 내려놓는 게 답입니다.",
  money:"여러 곳에 분산된 흐름을 정리해야 새는 곳이 보입니다.",
  work:"기획안이 많을수록 하나로 추려야 결과가 납니다.",
  caution:"환상은 결정의 적입니다. 사실과 상상을 분리해 두세요." },

{ id:"C08U", num:"8", name:"컵 8", nameEn:"Eight of Cups", suit:"cups", orientation:"upright", art:"cups",
  keyword:"떠남 · 다음으로 · 자기 회복",
  headline:'오늘은 "<em>익숙한 자리를 떠나야 하는 날</em>"입니다.',
  core:"같은 자리에 있어도 더 채워지지 않는다면 떠나야 할 신호입니다. 결정은 부드럽게.",
  love:"끌리지 않는 관계에 더 머무를 이유는 없습니다.",
  money:"수익이 멈춘 자리는 정리하고 다음을 보세요.",
  work:"이직·이동을 검토할 자리.",
  caution:"충동적인 도망과 정리는 다릅니다. 다음 자리를 그려 두고 움직이세요." },

{ id:"C09U", num:"9", name:"컵 9", nameEn:"Nine of Cups", suit:"cups", orientation:"upright", art:"cups",
  keyword:"만족 · 작은 행운 · 충만",
  headline:'오늘은 "<em>바라던 것이 손에 들어오는 날</em>"입니다.',
  core:"작은 소원이 이루어지는 자리. 받은 만큼 감사하면 다음이 또 옵니다.",
  love:"좋은 분위기가 자연스럽게 만들어지는 자리.",
  money:"작은 보너스·기대 수익이 따라옵니다.",
  work:"개인 성과가 빛나는 자리.",
  caution:"자만하면 다음이 식습니다." },

{ id:"C10U", num:"10", name:"컵 10", nameEn:"Ten of Cups", suit:"cups", orientation:"upright", art:"cups",
  keyword:"가정의 평화 · 깊은 안정",
  headline:'오늘은 "<em>가까운 사람들과 채워지는 날</em>"입니다.',
  core:"가족·연인·오랜 친구와의 시간이 큰 운이 됩니다.",
  love:"안정적인 관계로 한 단계 깊어질 자리.",
  money:"가족·공동 자산의 흐름에 길한 자리.",
  work:"동료와의 신뢰가 곧 성과로 이어집니다.",
  caution:"이상적인 그림에 집착하지 마세요. 사람은 사람일 뿐입니다." },

{ id:"CPU", num:"Page", name:"컵 페이지", nameEn:"Page of Cups", suit:"cups", orientation:"upright", art:"cups",
  keyword:"순수한 감정 · 영감",
  headline:'오늘은 "<em>마음의 첫 신호를 따르는 날</em>"입니다.',
  core:"가장 처음 떠오른 느낌을 가볍게 무시하지 마세요. 직관이 정답에 가깝습니다.",
  love:"수줍은 표현 한마디가 가장 큰 효과.",
  money:"새로운 콘텐츠·창작 수익의 단서가 보이는 자리.",
  work:"창의적인 아이디어가 떠오릅니다.",
  caution:"감정에만 매달리지 말고 실행으로 옮기세요." },

{ id:"CKnU", num:"Knight", name:"컵 기사", nameEn:"Knight of Cups", suit:"cups", orientation:"upright", art:"cups",
  keyword:"낭만 · 제안 · 부드러운 추진",
  headline:'오늘은 "<em>부드러운 제안이 통하는 날</em>"입니다.',
  core:"강하게 밀기보다 결을 맞춰 다가가야 답이 옵니다.",
  love:"세심한 표현이 큰 인상을 남깁니다.",
  money:"공감 기반 영업·중개가 잘 풀리는 자리.",
  work:"제안서·메일의 말투를 부드럽게 손보세요.",
  caution:"낭만에 빠져 현실 점검을 잊지 마세요." },

{ id:"CQU", num:"Queen", name:"컵 여왕", nameEn:"Queen of Cups", suit:"cups", orientation:"upright", art:"cups",
  keyword:"공감 · 직관 · 돌봄",
  headline:'오늘은 "<em>마음을 읽는 사람이 이기는 날</em>"입니다.',
  core:"분위기·표정·말 사이의 공기를 읽는 능력이 가장 큰 무기입니다.",
  love:"상대의 마음을 느끼는 자리. 다만 본인 감정도 함께 챙기세요.",
  money:"감정 노동을 자산으로 바꾸는 자리.",
  work:"상담·서비스·중재 자리에 잘 맞습니다.",
  caution:"남의 감정에 너무 휘둘리면 자신이 빕니다." },

{ id:"CKU", num:"King", name:"컵 왕", nameEn:"King of Cups", suit:"cups", orientation:"upright", art:"cups",
  keyword:"성숙한 감정 · 평정 · 안정",
  headline:'오늘은 "<em>흔들리지 않는 사람이 빛나는 날</em>"입니다.',
  core:"감정의 파도가 있어도 본인 중심을 지키면 주변이 따라옵니다.",
  love:"흔들리는 상대를 묵묵히 안아 주는 자리.",
  money:"감정 매매를 피하고 원칙대로 가세요.",
  work:"갈등 중재·고객 관리에서 빛나는 자리.",
  caution:"평정이 무감각이 되지 않게 자신도 표현하세요." },

/* ===================== SWORDS (검 · 바람) ===================== */
{ id:"S01U", num:"Ace", name:"검 에이스", nameEn:"Ace of Swords", suit:"swords", orientation:"upright", art:"swords",
  keyword:"명료 · 결단 · 진실",
  headline:'오늘은 "<em>한 칼에 정리되는 날</em>"입니다.',
  core:"오래 흐릿하던 자리가 한 번에 정리되는 자리. 결정하면 흔들리지 마세요.",
  love:"진심을 분명히 말할 자리.",
  money:"애매했던 계약·조건을 명확히 다시 정리하세요.",
  work:"문제의 핵심을 한 줄로 적어 보세요. 답이 보입니다.",
  caution:"단호함이 차가움이 되지 않게 결을 챙기세요." },

{ id:"S02U", num:"2", name:"검 2", nameEn:"Two of Swords", suit:"swords", orientation:"upright", art:"swords",
  keyword:"균형 · 망설임 · 보류",
  headline:'오늘은 "<em>결정을 잠시 미뤄도 되는 날</em>"입니다.',
  core:"정보가 부족할 땐 결정을 미루는 것도 결정입니다. 한 박자 뒤가 더 안전합니다.",
  love:"애매한 관계라면 무리해서 답을 강요하지 마세요.",
  money:"투자·매수 결정 보류가 안전.",
  work:"확실치 않은 합의는 서명 보류.",
  caution:"보류와 회피는 다릅니다. 보류엔 기한을 두세요." },

{ id:"S03U", num:"3", name:"검 3", nameEn:"Three of Swords", suit:"swords", orientation:"upright", art:"swords",
  keyword:"상처 · 슬픔 · 직면",
  headline:'오늘은 "<em>아픈 자리를 직시해야 하는 날</em>"입니다.',
  core:"피하기보다 마주 봐야 끝납니다. 묻어 두면 다음에 더 크게 옵니다.",
  love:"오래된 상처를 한 번 짚고 가야 할 자리.",
  money:"손실 인정이 다음 흐름의 시작입니다.",
  work:"피드백·지적을 방어하지 말고 기록해 두세요.",
  caution:"감정의 응축을 풀 곳이 필요한 자리. 혼자 끌어안지 마세요." },

{ id:"S04U", num:"4", name:"검 4", nameEn:"Four of Swords", suit:"swords", orientation:"upright", art:"swords",
  keyword:"휴식 · 회복 · 멈춤",
  headline:'오늘은 "<em>잠시 멈추는 게 약이 되는 날</em>"입니다.',
  core:"달려온 자리만큼 회복도 필요합니다. 오늘은 쉬는 것이 일하는 것보다 가치 있는 자리.",
  love:"감정 정리를 위한 거리감이 필요한 자리.",
  money:"공격적인 행동 보류. 안전 자산 점검만.",
  work:"무리한 일정 한 가지는 줄이세요.",
  caution:"멈춤이 도피가 되지 않게 기한을 두세요." },

{ id:"S05U", num:"5", name:"검 5", nameEn:"Five of Swords", suit:"swords", orientation:"upright", art:"swords",
  keyword:"갈등 · 자존심 · 이긴 듯한 패배",
  headline:'오늘은 "<em>이기고도 잃기 쉬운 날</em>"입니다.',
  core:"논리로는 이겨도 사람을 잃을 수 있는 자리. 이기는 방식까지 신경 쓰세요.",
  love:"말다툼에서 이겨도 거리가 멀어지면 의미 없습니다.",
  money:"단기 이익에 매몰돼 신뢰를 잃지 마세요.",
  work:"동료를 깎아내리는 발언은 부메랑이 됩니다.",
  caution:"자존심을 내려놓는 한마디가 큰 결과를 만듭니다." },

{ id:"S06U", num:"6", name:"검 6", nameEn:"Six of Swords", suit:"swords", orientation:"upright", art:"swords",
  keyword:"이동 · 전환 · 회복의 항해",
  headline:'오늘은 "<em>다음 자리로 옮기는 날</em>"입니다.',
  core:"무거운 자리를 떠나 더 잔잔한 자리로 옮길 흐름. 천천히, 그러나 확실히.",
  love:"불안정한 관계에서 벗어나기 좋은 자리.",
  money:"고비용 구조를 가벼운 구조로 옮길 자리.",
  work:"이직·이동을 검토할 자리.",
  caution:"짐을 다 들고 가지 마세요. 무게를 줄여야 빠릅니다." },

{ id:"S07U", num:"7", name:"검 7", nameEn:"Seven of Swords", suit:"swords", orientation:"upright", art:"swords",
  keyword:"전략 · 우회 · 기만 주의",
  headline:'오늘은 "<em>정면 대결보다 우회가 답인 날</em>"입니다.',
  core:"불리한 자리에선 정면으로 부딪치지 말고 우회로를 찾으세요. 다만 거짓말은 금물.",
  love:"숨겨진 마음·정보가 드러날 수 있는 자리. 솔직함이 답.",
  money:"화려한 제안 뒤를 한 번 더 보세요.",
  work:"전략적 후퇴도 실력입니다.",
  caution:"잔머리는 결국 들통. 정직한 우회와 기만은 다릅니다." },

{ id:"S08U", num:"8", name:"검 8", nameEn:"Eight of Swords", suit:"swords", orientation:"upright", art:"swords",
  keyword:"갇힘 · 자기 한계 · 시선의 함정",
  headline:'오늘은 "<em>스스로 묶어 둔 끈을 푸는 날</em>"입니다.',
  core:"안 된다고 믿고 있던 자리, 사실은 가능한 자리일 수 있습니다. 한 칸만 움직여 보세요.",
  love:"못할 거라는 생각이 가장 큰 장벽.",
  money:"안 된다고 단정 짓던 항목을 다시 검토.",
  work:"한계는 본인이 만든 경우가 많습니다.",
  caution:"피해의식에 너무 오래 머무르지 마세요." },

{ id:"S09U", num:"9", name:"검 9", nameEn:"Nine of Swords", suit:"swords", orientation:"upright", art:"swords",
  keyword:"불안 · 걱정 · 새벽의 머리",
  headline:'오늘은 "<em>걱정이 머리를 점령하기 쉬운 날</em>"입니다.',
  core:"머릿속 시나리오의 90%는 일어나지 않습니다. 실제 행동 한 가지로 바꿔 보세요.",
  love:"의심을 키우면 진짜 일이 됩니다.",
  money:"걱정만 하기보다 가계부 한 줄 점검.",
  work:"불안한 머리로는 결정 금물.",
  caution:"수면·식사 챙기는 게 가장 빠른 약입니다." },

{ id:"S10U", num:"10", name:"검 10", nameEn:"Ten of Swords", suit:"swords", orientation:"upright", art:"swords",
  keyword:"바닥 · 끝과 시작",
  headline:'오늘은 "<em>여기서가 끝인 날</em>"입니다.',
  core:"바닥을 짚었다면 더 떨어질 곳도 없습니다. 다음은 올라갈 일만 남았습니다.",
  love:"맞지 않는 관계의 마침이 보이는 자리.",
  money:"손실의 정리가 끝나는 자리.",
  work:"실패의 결산이 끝나는 자리. 배운 것만 정리하세요.",
  caution:"과한 비관은 다음 카드까지 가립니다." },

{ id:"SPU", num:"Page", name:"검 페이지", nameEn:"Page of Swords", suit:"swords", orientation:"upright", art:"swords",
  keyword:"호기심 · 관찰 · 빠른 학습",
  headline:'오늘은 "<em>듣고 묻는 사람이 이기는 날</em>"입니다.',
  core:"질문을 잘 던지는 사람이 답을 가져갑니다. 모를 땐 물어보세요.",
  love:"가벼운 호기심으로 시작하면 자연스럽습니다.",
  money:"새 시장·새 정보 학습이 길합니다.",
  work:"리서치·분석·자료 정리에 좋은 자리.",
  caution:"말은 가볍게, 글은 두 번 확인하세요." },

{ id:"SKnU", num:"Knight", name:"검 기사", nameEn:"Knight of Swords", suit:"swords", orientation:"upright", art:"swords",
  keyword:"속도 · 직진 · 추진",
  headline:'오늘은 "<em>빠르게 치고 나가는 날</em>"입니다.',
  core:"머뭇거리면 흐름이 빠집니다. 결정한 다음엔 한 번에 가세요.",
  love:"표현은 빠르게, 다만 결까지 챙겨서.",
  money:"단기 결단이 효과 있는 자리.",
  work:"속도 경쟁에서 앞서가는 자리.",
  caution:"폭주는 사고로 이어집니다. 안전 점검 한 번 더." },

{ id:"SQU", num:"Queen", name:"검 여왕", nameEn:"Queen of Swords", suit:"swords", orientation:"upright", art:"swords",
  keyword:"명확함 · 단호함 · 통찰",
  headline:'오늘은 "<em>분명하게 잘라야 하는 날</em>"입니다.',
  core:"감정을 잠시 내려놓고 사실만 보세요. 흐릿함이 가장 큰 적입니다.",
  love:"흐릿한 관계에 분명한 선을 그어야 할 자리.",
  money:"엄격한 가계 점검이 길합니다.",
  work:"의사결정 자리에서 단호한 한마디가 통합니다.",
  caution:"날카로움이 차가움이 되지 않게 결을 챙기세요." },

{ id:"SKU", num:"King", name:"검 왕", nameEn:"King of Swords", suit:"swords", orientation:"upright", art:"swords",
  keyword:"논리 · 권위 · 원칙",
  headline:'오늘은 "<em>원칙으로 가야 하는 날</em>"입니다.',
  core:"감정·동정에 흔들리면 흐름이 어그러집니다. 정해 둔 원칙대로 가세요.",
  love:"진지한 대화가 필요한 자리.",
  money:"법적·계약적 검토를 미루지 마세요.",
  work:"공정한 판단이 신뢰로 돌아옵니다.",
  caution:"원칙이 외고집이 되지 않게 다른 의견 한 번은 들어 두세요." },

/* ===================== PENTACLES (오각별 · 흙) ===================== */
{ id:"P01U", num:"Ace", name:"오각별 에이스", nameEn:"Ace of Pentacles", suit:"pentacles", orientation:"upright", art:"pentacles",
  keyword:"새로운 기회 · 실물 자산",
  headline:'오늘은 "<em>씨앗이 손에 들어오는 날</em>"입니다.',
  core:"실속 있는 기회가 들어오는 자리. 작아 보여도 끝까지 챙기면 큰 자산이 됩니다.",
  love:"진지한 관계로 발전할 수 있는 자리.",
  money:"새 수입·새 계좌·새 자산의 출발점.",
  work:"안정적인 새 일·새 자리가 들어옵니다.",
  caution:"오래 가는 자산은 빨리 만들어지지 않습니다." },

{ id:"P02U", num:"2", name:"오각별 2", nameEn:"Two of Pentacles", suit:"pentacles", orientation:"upright", art:"pentacles",
  keyword:"저글링 · 균형 · 유연성",
  headline:'오늘은 "<em>여러 가지를 동시에 굴려야 하는 날</em>"입니다.',
  core:"한 가지에만 매달리지 말고 흐름 전체를 굴려 보세요. 균형이 곧 실력입니다.",
  love:"바쁜 일정 속에서도 짧은 챙김이 큰 효과.",
  money:"수입·지출 균형 점검 자리.",
  work:"멀티 프로젝트 운영 자리. 우선순위만 챙기세요.",
  caution:"균형 잡힌 듯 보여도 자기 회복은 잊지 마세요." },

{ id:"P03U", num:"3", name:"오각별 3", nameEn:"Three of Pentacles", suit:"pentacles", orientation:"upright", art:"pentacles",
  keyword:"협업 · 숙련 · 신뢰",
  headline:'오늘은 "<em>전문성이 통하는 날</em>"입니다.',
  core:"본인의 실력을 분명히 드러낼 자리. 협업에서도 좋은 평을 받습니다.",
  love:"존중 기반의 관계가 깊어집니다.",
  money:"전문성을 기반으로 한 수익이 길합니다.",
  work:"팀워크가 곧 성과로 이어지는 자리.",
  caution:"공로를 혼자 가져가지 마세요. 곁을 챙기는 한마디가 결정적." },

{ id:"P04U", num:"4", name:"오각별 4", nameEn:"Four of Pentacles", suit:"pentacles", orientation:"upright", art:"pentacles",
  keyword:"보존 · 안정 · 집착 주의",
  headline:'오늘은 "<em>지키는 데 집중하는 날</em>"입니다.',
  core:"새로 확장하기보다 가진 것을 단단히 지킬 자리. 다만 너무 움켜쥐면 흐름이 막힙니다.",
  love:"통제하려는 마음을 한 발 늦추세요.",
  money:"방어적 운용이 길합니다.",
  work:"기존 거래처·자리를 단단히 유지하세요.",
  caution:"인색함은 결국 흐름을 막습니다." },

{ id:"P05U", num:"5", name:"오각별 5", nameEn:"Five of Pentacles", suit:"pentacles", orientation:"upright", art:"pentacles",
  keyword:"결핍 · 소외 · 도움 청하기",
  headline:'오늘은 "<em>혼자 끌어안지 말아야 하는 날</em>"입니다.',
  core:"힘들 땐 손을 내미는 게 가장 빠른 길. 도움을 청하는 것도 능력입니다.",
  love:"상처를 혼자 묻어두지 마세요.",
  money:"긴급 자금이 필요하면 정공법으로.",
  work:"동료·상사에게 분명히 어려움을 알리세요.",
  caution:"자존심이 가장 큰 비용이 될 수 있습니다." },

{ id:"P06U", num:"6", name:"오각별 6", nameEn:"Six of Pentacles", suit:"pentacles", orientation:"upright", art:"pentacles",
  keyword:"나눔 · 흐름 · 공정",
  headline:'오늘은 "<em>나누면 돌아오는 날</em>"입니다.',
  core:"받기만 하기보다 적당히 나누는 자리. 흐름이 만들어집니다.",
  love:"받은 만큼 표현해 주세요.",
  money:"기부·후원·정당한 대가 지급이 길합니다.",
  work:"공로를 분명히 나누면 다음이 단단해집니다.",
  caution:"베풂이 일방적이 되면 관계가 흐려집니다." },

{ id:"P07U", num:"7", name:"오각별 7", nameEn:"Seven of Pentacles", suit:"pentacles", orientation:"upright", art:"pentacles",
  keyword:"인내 · 장기적 시야",
  headline:'오늘은 "<em>심어 둔 자리를 기다리는 날</em>"입니다.',
  core:"결과가 안 보인다고 뒤집지 마세요. 오래 걸리는 자리는 시간이 답입니다.",
  love:"오래 만난 인연일수록 천천히 깊어집니다.",
  money:"장기 투자·적금 흐름이 길합니다.",
  work:"긴 호흡의 프로젝트는 중간 점검만.",
  caution:"조급함이 다 망칩니다." },

{ id:"P08U", num:"8", name:"오각별 8", nameEn:"Eight of Pentacles", suit:"pentacles", orientation:"upright", art:"pentacles",
  keyword:"숙련 · 반복 · 장인",
  headline:'오늘은 "<em>꾸준함이 실력이 되는 날</em>"입니다.',
  core:"단순 반복이 지겨워도 그게 길이 됩니다. 오늘 쌓은 게 다음 자리의 발판입니다.",
  love:"꾸준한 챙김이 가장 큰 매력.",
  money:"꾸준한 적립 흐름이 길합니다.",
  work:"숙련도가 인정받는 자리.",
  caution:"의미를 잃지 않게 작은 보상은 챙기세요." },

{ id:"P09U", num:"9", name:"오각별 9", nameEn:"Nine of Pentacles", suit:"pentacles", orientation:"upright", art:"pentacles",
  keyword:"자립 · 풍요 · 정원",
  headline:'오늘은 "<em>스스로 채운 자리가 빛나는 날</em>"입니다.',
  core:"누군가 채워 주길 기다리지 말고 스스로 가꿔 온 자리를 즐기세요.",
  love:"혼자도 충만한 사람이 오히려 매력적입니다.",
  money:"안정적인 자산 흐름이 자리잡는 자리.",
  work:"독립적 영역에서 빛납니다.",
  caution:"자립이 고립이 되지 않게 사람 자리도 챙기세요." },

{ id:"P10U", num:"10", name:"오각별 10", nameEn:"Ten of Pentacles", suit:"pentacles", orientation:"upright", art:"pentacles",
  keyword:"가문 · 장기 자산 · 안정의 완성",
  headline:'오늘은 "<em>큰 흐름이 단단해지는 날</em>"입니다.',
  core:"개인의 성과가 가족·공동체의 자산으로 이어지는 자리. 길게 갈 구조를 만드세요.",
  love:"장기적 약속·결혼·가족 단위 결정에 길합니다.",
  money:"부동산·장기 자산 검토에 좋은 자리.",
  work:"오래 갈 시스템을 다지는 자리.",
  caution:"전통과 관습에 너무 묶이지는 마세요." },

{ id:"PPU", num:"Page", name:"오각별 페이지", nameEn:"Page of Pentacles", suit:"pentacles", orientation:"upright", art:"pentacles",
  keyword:"학습 · 실용 · 천천히 시작",
  headline:'오늘은 "<em>기본기를 다지는 날</em>"입니다.',
  core:"화려한 결과보다 기초를 다질 자리. 작은 실력 한 가지가 평생 자산이 됩니다.",
  love:"천천히, 진지하게 다가가는 흐름.",
  money:"공부 기반 투자가 길합니다.",
  work:"새 분야의 기초 학습이 길합니다.",
  caution:"빠른 결과 욕심을 잠시 내려두세요." },

{ id:"PKnU", num:"Knight", name:"오각별 기사", nameEn:"Knight of Pentacles", suit:"pentacles", orientation:"upright", art:"pentacles",
  keyword:"성실 · 묵묵함 · 신뢰",
  headline:'오늘은 "<em>꾸준한 사람이 가져가는 날</em>"입니다.',
  core:"화려함은 없어도 흔들리지 않는 자리. 약속을 지키는 한마디가 가장 큰 무기입니다.",
  love:"묵묵한 챙김이 신뢰로 쌓입니다.",
  money:"장기 적금·연금 흐름에 길합니다.",
  work:"마감을 지키는 사람이 다음 자리도 받습니다.",
  caution:"단조로움이 지치지 않게 작은 변주를 두세요." },

{ id:"PQU", num:"Queen", name:"오각별 여왕", nameEn:"Queen of Pentacles", suit:"pentacles", orientation:"upright", art:"pentacles",
  keyword:"실용 · 다정함 · 살림의 힘",
  headline:'오늘은 "<em>살림이 곧 실력이 되는 날</em>"입니다.',
  core:"실속과 다정함을 동시에 챙기는 자리. 큰 흐름은 작은 챙김에서 나옵니다.",
  love:"안정감 있는 분위기가 매력.",
  money:"가계 운용·생활 자산 관리에 길합니다.",
  work:"디테일 관리에서 빛납니다.",
  caution:"본인 회복 시간을 빼먹지 마세요." },

{ id:"PKU", num:"King", name:"오각별 왕", nameEn:"King of Pentacles", suit:"pentacles", orientation:"upright", art:"pentacles",
  keyword:"부의 통솔 · 신뢰 · 풍요의 완성",
  headline:'오늘은 "<em>실력으로 신뢰를 얻는 날</em>"입니다.',
  core:"숫자·결과·평판이 모두 받쳐주는 자리. 단단함을 흔들지 마세요.",
  love:"든든한 존재감이 매력.",
  money:"큰 단위 자산 결정에 길합니다.",
  work:"리더의 자리에서 빛납니다.",
  caution:"인색함은 가장 큰 약점이 됩니다." },

/* ===================== MINOR ARCANA — 역방향 (요약형) ===================== */
{ id:"W01R", num:"Ace", name:"지팡이 에이스 (역)", nameEn:"Ace of Wands · Reversed", suit:"wands", orientation:"reversed", art:"wands",
  keyword:"지연된 시작 · 의욕 저하",
  headline:'오늘은 "<em>시동이 잘 안 걸리는 날</em>"입니다.',
  core:"동기가 약하다면 무리하게 시작하지 말고 환경부터 정리하세요. 책상 한 칸이 의외로 시동이 됩니다.",
  love:"표현이 어색하다면 짧은 안부 한마디부터.",
  money:"새 진입 보류. 가진 것 점검 먼저.",
  work:"새 일을 띄우기보단 묵은 일 마무리.",
  caution:"의욕 없는 자신을 비난하지 마세요." },

{ id:"W05R", num:"5", name:"지팡이 5 (역)", nameEn:"Five of Wands · Reversed", suit:"wands", orientation:"reversed", art:"wands",
  keyword:"내부 갈등 · 묻어둔 불씨",
  headline:'오늘은 "<em>안에서 곪지 않게 풀어야 하는 날</em>"입니다.',
  core:"겉으론 잠잠해도 안에선 부글거리는 자리. 짧게라도 짚고 가세요.",
  love:"덮어둔 갈등은 다음에 더 크게 옵니다.",
  money:"공동 명의·합의 사항을 다시 점검.",
  work:"팀 내 불만은 짧게 듣고 길게 행동.",
  caution:"평화로워 보일수록 한 번 더 확인." },

{ id:"W08R", num:"8", name:"지팡이 8 (역)", nameEn:"Eight of Wands · Reversed", suit:"wands", orientation:"reversed", art:"wands",
  keyword:"지연 · 늦은 소식",
  headline:'오늘은 "<em>흐름이 한 박자 늦어지는 날</em>"입니다.',
  core:"기다리던 답이 늦어질 수 있는 자리. 다른 흐름으로 시간을 채우세요.",
  love:"연락 늦어진다고 의심하지 마세요.",
  money:"입금·결제 지연 가능. 미리 안내.",
  work:"마감 보수적으로 잡으세요.",
  caution:"기다림이 길어질수록 다른 일에 집중하세요." },

{ id:"W10R", num:"10", name:"지팡이 10 (역)", nameEn:"Ten of Wands · Reversed", suit:"wands", orientation:"reversed", art:"wands",
  keyword:"번아웃 · 위임 필요",
  headline:'오늘은 "<em>내려놓아야 다음이 보이는 날</em>"입니다.',
  core:"한 짐만이라도 위임하세요. 다 안고 가다 모두 무너집니다.",
  love:"감정 노동이 과한 관계 점검.",
  money:"고정비 한 항목 줄이기.",
  work:"업무 분담 다시 그리세요.",
  caution:"몸 신호 무시 금물." },

{ id:"C05R", num:"5", name:"컵 5 (역)", nameEn:"Five of Cups · Reversed", suit:"cups", orientation:"reversed", art:"cups",
  keyword:"회복 · 미련 정리",
  headline:'오늘은 "<em>남은 것이 다시 보이는 날</em>"입니다.',
  core:"잃은 자리에 갇혀 있었다면 오늘 시야가 트입니다. 남아 있는 자원을 챙기세요.",
  love:"옛 미련이 가벼워지는 자리.",
  money:"손실 회복 가능 자리부터 시작.",
  work:"실패에서 배운 점을 다음에 적용.",
  caution:"되돌아보기는 짧게, 앞으로는 길게." },

{ id:"C07R", num:"7", name:"컵 7 (역)", nameEn:"Seven of Cups · Reversed", suit:"cups", orientation:"reversed", art:"cups",
  keyword:"명확한 선택 · 환상 정리",
  headline:'오늘은 "<em>흐릿함이 걷히는 날</em>"입니다.',
  core:"여러 갈래의 환상이 사라지고 한 가지 길이 분명해지는 자리.",
  love:"이상형을 내려놓고 사실을 보세요.",
  money:"분산된 흐름을 정리할 자리.",
  work:"기획안을 한 줄로 추리세요.",
  caution:"환상을 잃는 게 어른이 되는 자리." },

{ id:"C08R", num:"8", name:"컵 8 (역)", nameEn:"Eight of Cups · Reversed", suit:"cups", orientation:"reversed", art:"cups",
  keyword:"머무름 · 떠나지 못함",
  headline:'오늘은 "<em>떠나야 함을 알면서 못 떠나는 날</em>"입니다.',
  core:"이미 답은 정해진 자리. 두려움 때문에 다음 발이 안 떨어지는 거라면 작은 한 걸음부터.",
  love:"미련은 가벼울수록 좋습니다.",
  money:"손해 자리를 더 묶지 마세요.",
  work:"이동 검토를 미루지 마세요.",
  caution:"머무름의 이유가 두려움이라면 떠나는 게 맞습니다." },

{ id:"S03R", num:"3", name:"검 3 (역)", nameEn:"Three of Swords · Reversed", suit:"swords", orientation:"reversed", art:"swords",
  keyword:"치유 · 상처의 끝",
  headline:'오늘은 "<em>아픈 자리가 닫히는 날</em>"입니다.',
  core:"오래 끌어온 상처가 한 매듭 지어지는 자리. 회복의 첫날이 될 수 있습니다.",
  love:"용서가 가벼워지는 자리.",
  money:"손실의 정리가 끝나는 자리.",
  work:"오해가 풀리는 자리.",
  caution:"낫는 동안엔 무리 금물." },

{ id:"S09R", num:"9", name:"검 9 (역)", nameEn:"Nine of Swords · Reversed", suit:"swords", orientation:"reversed", art:"swords",
  keyword:"불안의 해소 · 빛이 들어옴",
  headline:'오늘은 "<em>걱정이 한 톤 가벼워지는 날</em>"입니다.',
  core:"머릿속의 그림이 실제와 다르다는 게 보이는 자리. 사실을 적어 보세요.",
  love:"의심을 사실로 확인하면 가벼워집니다.",
  money:"막연한 불안을 숫자로 확인.",
  work:"걱정한 상황의 실체를 점검.",
  caution:"수면·식사 챙기는 게 우선." },

{ id:"S10R", num:"10", name:"검 10 (역)", nameEn:"Ten of Swords · Reversed", suit:"swords", orientation:"reversed", art:"swords",
  keyword:"회복의 시작 · 바닥에서 일어남",
  headline:'오늘은 "<em>다시 일어서는 날</em>"입니다.',
  core:"가장 낮은 자리에서 한 칸 올라가는 자리. 한 걸음만 떼면 다음이 보입니다.",
  love:"끝났던 관계가 다른 형태로 정리됩니다.",
  money:"바닥에서 흐름이 살아납니다.",
  work:"새로 시작할 자리가 보입니다.",
  caution:"무리하게 한꺼번에 가지 마세요." },

{ id:"P04R", num:"4", name:"오각별 4 (역)", nameEn:"Four of Pentacles · Reversed", suit:"pentacles", orientation:"reversed", art:"pentacles",
  keyword:"움켜쥠 풀기 · 흐름 회복",
  headline:'오늘은 "<em>쥐고 있던 손을 펴는 날</em>"입니다.',
  core:"너무 단단히 잡고 있던 자리가 풀리는 흐름. 베풂이 다시 흐름을 만듭니다.",
  love:"통제의 끈을 한 칸 풀어 주세요.",
  money:"필요한 곳엔 쓰는 게 운입니다.",
  work:"숨겨둔 정보·노하우를 공유.",
  caution:"낭비와 흐름은 다릅니다. 분별만 챙기세요." },

{ id:"P05R", num:"5", name:"오각별 5 (역)", nameEn:"Five of Pentacles · Reversed", suit:"pentacles", orientation:"reversed", art:"pentacles",
  keyword:"회복 · 구원의 손길",
  headline:'오늘은 "<em>도움이 들어오는 날</em>"입니다.',
  core:"오래 어두웠던 자리에 빛이 들어오는 자리. 손 내미는 사람을 거절하지 마세요.",
  love:"위로의 손길이 큰 의미가 됩니다.",
  money:"긴급 자금·복지·환급의 흐름이 옵니다.",
  work:"도움 요청에 좋은 응답이 옵니다.",
  caution:"받은 것은 잊지 말고 갚으세요." },

/* ===================== 보너스 : 난다사주 특별 카드 ===================== */
{ id:"N01", num:"特", name:"북두칠성", nameEn:"The Seven Stars", suit:"special", orientation:"upright", art:"star",
  keyword:"방향 · 지표 · 인생의 별",
  headline:'오늘은 "<em>본인의 별을 찾는 날</em>"입니다.',
  core:"길을 잃은 듯한 자리에서 가장 오래된 별이 답을 줍니다. 자신이 본래 어디로 가고 싶었는지 적어 보세요.",
  love:"흐릿하던 관계의 방향이 분명해지는 자리.",
  money:"장기 목표를 기준으로 자산 배분 점검.",
  work:"커리어의 큰 방향을 정리할 자리.",
  caution:"잠깐의 유행에 흔들리지 마세요." },

{ id:"N02", num:"特", name:"백호", nameEn:"The White Tiger", suit:"special", orientation:"upright", art:"strength",
  keyword:"기개 · 단호함 · 자기 보호",
  headline:'오늘은 "<em>흔들리지 않는 사람이 빛나는 날</em>"입니다.',
  core:"외부의 흔듦에도 본인 중심을 잡으면 흐름이 따라옵니다. 약한 모습을 보이지 않는 게 답.",
  love:"단단한 모습이 매력이 됩니다.",
  money:"공격적 운용보다 보호의 자세.",
  work:"본인 영역에 대한 분명한 선이 필요한 자리.",
  caution:"단호함이 적을 만들지 않게 결을 챙기세요." },

{ id:"N03", num:"特", name:"청룡", nameEn:"The Azure Dragon", suit:"special", orientation:"upright", art:"trumpet",
  keyword:"승천 · 큰 흐름 · 도약",
  headline:'오늘은 "<em>큰 흐름이 등을 미는 날</em>"입니다.',
  core:"본인보다 큰 흐름이 작동하는 자리. 무리하지 않고 흐름에 올라타기만 하면 됩니다.",
  love:"운명적인 인연의 신호가 오는 자리.",
  money:"큰 기회의 단서가 보입니다. 빠른 캐치.",
  work:"승진·이직·도약 자리에 길합니다.",
  caution:"흐름은 빠를수록 발 헛디딤도 쉽습니다. 안전 점검." },

{ id:"N04", num:"特", name:"주작", nameEn:"The Vermilion Bird", suit:"special", orientation:"upright", art:"sun",
  keyword:"열정 · 표현 · 빛",
  headline:'오늘은 "<em>마음을 분명히 드러내는 날</em>"입니다.',
  core:"감춰 두던 마음을 표현해도 좋은 자리. 솔직한 표현이 가장 큰 운입니다.",
  love:"분명한 고백·표현이 통하는 자리.",
  money:"개인 브랜드·표현 기반 수익에 길합니다.",
  work:"발표·제안·콘텐츠 흐름이 좋습니다.",
  caution:"열정이 과욕이 되지 않게 한 박자만." },

{ id:"N05", num:"特", name:"현무", nameEn:"The Black Tortoise", suit:"special", orientation:"upright", art:"vessel",
  keyword:"오래된 지혜 · 안정 · 보호",
  headline:'오늘은 "<em>천천히 가는 사람이 멀리 가는 날</em>"입니다.',
  core:"빠른 결과보다 단단한 기반이 답인 자리. 오래 묵힌 노하우가 빛납니다.",
  love:"오래 함께한 인연의 가치를 다시 보세요.",
  money:"장기 자산 운용에 길합니다.",
  work:"경험·노하우가 인정받는 자리.",
  caution:"안정에만 머무르면 흐름이 멈춥니다." },

{ id:"N06", num:"特", name:"삼신할미", nameEn:"The Three-Spirit Grandmother", suit:"special", orientation:"upright", art:"empress",
  keyword:"보살핌 · 결실 · 인연",
  headline:'오늘은 "<em>오래된 인연이 도와주는 날</em>"입니다.',
  core:"가족·연장자·오래된 인연에서 좋은 흐름이 옵니다. 안부 한마디가 큰 효과.",
  love:"가까운 인연이 새 인연을 소개해 줄 수 있는 자리.",
  money:"가족 단위 자산 흐름에 길합니다.",
  work:"멘토·선배의 한마디가 결정적.",
  caution:"받기만 하지 마세요. 작은 표현이 흐름을 만듭니다." },

{ id:"N07", num:"特", name:"용궁", nameEn:"The Dragon Palace", suit:"special", orientation:"upright", art:"cups",
  keyword:"숨겨진 보물 · 깊은 곳의 답",
  headline:'오늘은 "<em>깊이 들어가야 보이는 날</em>"입니다.',
  core:"표면의 답으로는 부족한 자리. 한 층 더 들어가 보면 진짜 답이 있습니다.",
  love:"상대의 깊은 마음을 들여다볼 자리.",
  money:"숨겨진 자산·잊고 있던 권리 점검.",
  work:"드러나지 않은 핵심 정보를 찾는 자리.",
  caution:"깊이가 두려움이 되지 않게 한 호흡씩." },

{ id:"N08", num:"特", name:"동방삭", nameEn:"The Long-lived Sage", suit:"special", orientation:"upright", art:"lantern",
  keyword:"긴 호흡 · 인내의 시간",
  headline:'오늘은 "<em>긴 시간을 두고 보는 날</em>"입니다.',
  core:"한 달, 일 년 단위로 보면 지금의 답답함이 작아 보입니다. 시야의 거리를 늘리세요.",
  love:"성급한 결론을 피하세요.",
  money:"단기 등락에 흔들리지 마세요.",
  work:"커리어의 큰 호흡을 잡을 자리.",
  caution:"긴 호흡이 게으름이 되지 않게 매일의 한 가지는 챙기세요." },

{ id:"N09", num:"特", name:"심청의 연꽃", nameEn:"The Lotus of Sim Cheong", suit:"special", orientation:"upright", art:"star",
  keyword:"희생 후의 결실 · 부활",
  headline:'오늘은 "<em>그동안의 정성이 보답받는 날</em>"입니다.',
  core:"누군가를 위해 오래 헌신했다면 그 결실이 돌아오는 자리. 다만 받을 줄도 알아야 합니다.",
  love:"오래된 짝사랑·짝짝이 관계의 흐름이 정리됩니다.",
  money:"오래 묵힌 자산의 흐름이 살아납니다.",
  work:"오래 준비한 자리에서 결과가 나옵니다.",
  caution:"보답을 못 받았다고 자신을 갉아먹지 마세요." },

{ id:"N10", num:"特", name:"호랑이 담배 피던 시절", nameEn:"In the Ancient Days", suit:"special", orientation:"upright", art:"wreath",
  keyword:"시간의 흐름 · 오래된 지혜",
  headline:'오늘은 "<em>옛 방식이 답인 날</em>"입니다.',
  core:"새 도구·새 방식이 답이 아닌 자리. 어른의 방식, 옛날 노하우 한 가지가 결정적입니다.",
  love:"오래된 인연의 조언이 의외로 큽니다.",
  money:"오래된 자산·옛 거래처를 다시 보세요.",
  work:"기본기·정공법이 가장 빠른 자리.",
  caution:"옛것에 매몰돼 새 흐름을 무시하지는 마세요." }

];

/* ============================================================
   HEALTH (건강운) — 카드 ID별 건강 운세
   기존 카드의 love(연애), money(금전), work(일/사업)와 함께
   카테고리 선택 시 사용됩니다.
   ============================================================ */
const HEALTH = {
  // ===== Major Arcana — 정방향 =====
  M00U:"오늘은 가볍게 시작하는 게 약. 안 가본 산책로 한 번, 새 운동 한 가지. 작은 호기심이 활력을 만듭니다.",
  M01U:"집중력이 높은 자리. 규칙적인 식사·수면이 곧 회복입니다. 가진 루틴을 끝까지 쓰세요.",
  M02U:"몸의 신호에 귀 기울일 자리. 작은 통증·피로를 무시하지 마세요. 직관이 정확한 날입니다.",
  M03U:"따뜻한 자기 돌봄이 답. 좋은 식사·충분한 수면. 자신을 채워야 흐름이 돌아옵니다.",
  M04U:"규칙적 운동·식단이 빛납니다. 한 번 정해 두면 흔들림이 줄어듭니다. 자기 관리가 곧 권위입니다.",
  M05U:"검증된 방식이 안전. 새 도전보다 기본기. 미뤄둔 정기 검진 챙기기에 좋은 자리.",
  M06U:"같이 움직이는 활동이 약. 같이 걷고 같이 먹는 시간이 몸을 살립니다.",
  M07U:"활동량을 늘릴 자리. 다만 무리는 금물. 속도 조절이 핵심입니다.",
  M08U:"참는 힘이 곧 면역력. 화를 누르고 호흡을 길게. 부드러운 마음이 몸을 살립니다.",
  M09U:"혼자만의 회복 시간이 약. SNS 줄이고 산책·독서. 고요한 자리에서 몸이 풀립니다.",
  M10U:"흐름이 가벼운 자리. 새 운동·식단 도전에 길합니다. 변화에 몸이 잘 반응합니다.",
  M11U:"균형이 핵심. 일·휴식, 활동·쉼, 식사·운동. 한쪽으로 치우치면 무너집니다.",
  M12U:"잠시 멈추는 게 약. 시야를 바꾸면 답이 보입니다. 조용한 멈춤이 회복으로 이어집니다.",
  M13U:"안 좋은 습관 하나 끊을 자리. 야식·과음·늦수면 중 한 가지를 멈춰 보세요.",
  M14U:"균형 잡힌 식사·운동이 길합니다. 극단 피하고 중간을 잡으세요. 천천히 섞이는 회복.",
  M15U:"중독성 자극을 점검할 자리. 알면서 못 끊는 것 한 가지를 마주하세요.",
  M16U:"참아 온 통증·피로가 터질 수 있습니다. 일정을 줄이고 몸이 보내는 신호에 응답하세요.",
  M17U:"다시 빛이 드는 회복기. 햇볕·환기·물 챙기기. 작은 활력이 몸 전체를 살립니다.",
  M18U:"흐릿한 컨디션 주의. 무리한 판단·결정 금물. 충분히 자고 다음 날 확인하세요.",
  M19U:"활력이 살아나는 자리. 햇볕·산책·웃음. 가볍게 움직일수록 몸이 더 가벼워집니다.",
  M20U:"지난 컨디션을 점검할 자리. 미뤄둔 검진·운동을 다시 시작하기 좋습니다.",
  M21U:"한 주기의 회복이 마무리되는 자리. 다음 단계의 운동·식단 계획을 짜기 좋습니다.",

  // ===== Major Arcana — 역방향 =====
  M00R:"준비 없이 무리하면 부상. 새 운동 시작 전 워밍업·스트레칭 챙기세요.",
  M01R:"잔재주로는 안 됩니다. 검증된 운동·식단으로 돌아가세요.",
  M02R:"감정 과부하 주의. 가슴 답답함·두통 신호를 무시하지 마세요.",
  M03R:"챙겨주다 자기가 비는 자리. 자기 돌봄을 1순위로 두세요.",
  M04R:"무리한 자기 통제는 역효과. 부드러운 회복이 답입니다.",
  M05R:"관성적 식습관 점검할 자리. 오래된 습관 중 한 가지만 바꿔 보세요.",
  M06R:"함께 있어도 외로움이 몸을 무겁게 합니다. 솔직한 대화가 약.",
  M07R:"과속 주의. 운동 강도 한 칸 낮추세요. 부상이 가장 큰 적입니다.",
  M08R:"참기만 하다 터지기 쉬운 자리. 새는 곳은 적당히 풀어 주세요.",
  M09R:"너무 닫혀 있으면 우울이 깊어집니다. 한 사람이라도 만나기.",
  M10R:"컨디션이 정체된 자리. 기다리기보다 한 가지 행동으로 바꾸세요.",
  M11R:"불균형이 표가 나는 자리. 한쪽이 과한 습관을 점검하세요.",
  M12R:"무의미한 인내가 몸을 갉아먹습니다. 쉬는 결단이 필요합니다.",
  M13R:"끊어야 할 습관에 미련이 남은 자리. 작은 단절부터 시작하세요.",
  M14R:"과한 한쪽이 균형을 무너뜨립니다. 술·음식·자극의 양을 점검.",
  M15R:"중독에서 한 칸 빠져나오는 자리. 작은 결단이 큰 자유로 이어집니다.",
  M16R:"균열을 직시할 자리. 검진·점검 미루지 마세요.",
  M17R:"회복이 느린 자리. 남과 비교 멈추고 본인 속도로 가세요.",
  M18R:"흐릿함이 걷히는 자리. 드러난 사실을 마주할 용기가 필요합니다.",
  M19R:"기력이 한 박자 떨어진 자리. 페이스 조절이 답.",
  M20R:"같은 부상·증상 반복. 원인을 다른 곳에서 찾아보세요.",
  M21R:"마지막 한 끗이 부족한 자리. 마무리 점검에 시간을 들이세요.",

  // ===== Wands =====
  W01U:"의욕이 살아나는 자리. 새 운동 시작에 길합니다. 첫 며칠이 핵심.",
  W02U:"장기 계획을 짤 자리. 운동·식단의 큰 그림을 그리세요.",
  W03U:"심어 둔 자리가 결실. 꾸준한 운동의 결과가 드러나는 자리.",
  W04U:"함께 즐기는 활동이 약. 모임 후 회복도 잊지 마세요.",
  W05U:"격한 활동이 좋지만 무리는 금물. 경쟁심에 무리하지 마세요.",
  W06U:"인정받는 자리. 다만 과시하다 부상 주의.",
  W07U:"본인 페이스 지킬 자리. 남이 흔들어도 본인 루틴 유지.",
  W08U:"빠르게 진행되는 자리. 다만 식사 거르기 쉬우니 챙기세요.",
  W09U:"마지막 한 발이 남은 자리. 여기서 멈추지 마세요.",
  W10U:"짐을 줄여야 회복. 일정 한 가지 내려놓기.",
  WPU :"새 운동·새 식단 시도에 길. 가볍게 시작하세요.",
  WKnU:"속도가 핵심. 다만 폭주는 부상으로 이어집니다.",
  WQU :"당당함이 자세를 만듭니다. 어깨 펴고 호흡 길게.",
  WKU :"큰 방향이 잡힌 자리. 장기 루틴을 정착시키세요.",

  // ===== Cups =====
  C01U:"감정 회복의 자리. 마음이 풀리면 몸도 따라옵니다.",
  C02U:"마음 통하는 사람과의 시간이 약. 짧은 만남이라도 효과 큼.",
  C03U:"좋은 자리 즐기되 회복도 챙기세요. 다음 날 페이스 조절.",
  C04U:"익숙한 운동을 다시 보세요. 잊고 있던 효과를 발견할 자리.",
  C05U:"슬픔에 갇히면 몸도 무거워집니다. 남아 있는 자원을 보세요.",
  C06U:"옛 친구·옛 활동이 약. 추억 속 운동을 다시 한 번.",
  C07U:"너무 많은 선택지로 흐릿한 자리. 한 가지만 시작하세요.",
  C08U:"익숙한 자리를 떠나는 회복. 환경을 바꾸면 몸도 가벼워집니다.",
  C09U:"작은 만족이 회복으로. 자신에게 한 가지 챙겨 주세요.",
  C10U:"가족·친밀한 자리에서 회복. 함께 식사하는 시간이 약입니다.",
  CPU :"직관 따라 가벼운 운동. 마음에 끌리는 것이 답.",
  CKnU:"부드러운 운동이 길. 요가·수영처럼 결을 맞추는 운동.",
  CQU :"공감 노동이 몸을 무겁게 합니다. 자기 시간 확보가 우선.",
  CKU :"흔들리지 않는 평정이 약. 명상·호흡 챙기기.",

  // ===== Swords =====
  S01U:"한 칼에 정리되는 자리. 안 좋은 습관 명확히 끊을 때.",
  S02U:"결정을 미뤄도 되는 자리. 검진 결과 기다림에 좋음.",
  S03U:"상처를 마주할 자리. 우울감을 혼자 끌어안지 마세요.",
  S04U:"쉬는 것이 약. 무리한 일정 줄이고 잠 챙기기.",
  S05U:"격한 갈등이 몸을 갉음. 자존심 내려놓는 한마디.",
  S06U:"환경을 옮기는 회복. 한적한 곳으로 여행 길.",
  S07U:"정면 대결은 피로. 우회·휴식이 답입니다.",
  S08U:"스스로 한계 만든 자리. 가능한 한 가지부터 시도.",
  S09U:"걱정이 잠을 갉아먹습니다. 수면·식사 챙기기가 우선.",
  S10U:"바닥에서 일어나는 자리. 작은 회복부터 다시 시작.",
  SPU :"정보 정리가 회복. 검진 결과·증상을 기록하세요.",
  SKnU:"빠른 결정이 좋지만 무리한 운동은 금물.",
  SQU :"명확한 자기 점검. 흐릿한 컨디션을 데이터로 정리.",
  SKU :"원칙대로 가는 자리. 정해진 루틴을 흔들지 마세요.",

  // ===== Pentacles =====
  P01U:"실질적 회복의 자리. 몸에 좋은 음식 한 가지부터 챙기세요.",
  P02U:"여러 가지 균형 잡을 자리. 운동·휴식·식사 모두 챙기기.",
  P03U:"전문가의 도움 받기 좋은 자리. 트레이너·의사 상담.",
  P04U:"보존이 핵심. 무리한 신규 시도보다 기본 유지.",
  P05U:"결핍 신호. 영양·수면·운동 중 새는 곳을 점검하세요.",
  P06U:"나누는 활동이 약. 함께 운동·함께 식사.",
  P07U:"장기적 인내가 결과를 만듭니다. 매일 한 가지 꾸준히.",
  P08U:"반복이 곧 실력. 단순한 운동을 매일 같은 시간에.",
  P09U:"스스로 가꾼 자리가 빛납니다. 자기만의 루틴을 즐기세요.",
  P10U:"장기 자산처럼 몸도 길게. 가족 단위 건강 점검에 좋은 자리.",
  PPU :"기초 학습이 답. 운동·영양의 기본을 공부하세요.",
  PKnU:"꾸준함이 핵심. 매일 같은 시간 같은 운동.",
  PQU :"살림이 곧 건강. 자기 식사·수면 챙기기.",
  PKU :"큰 그림의 건강 운용. 장기 검진 계획을 세우세요.",

  // ===== Minor Reversed =====
  W01R:"의욕이 안 나는 자리. 환경부터 정리하세요.",
  W05R:"안에 곪는 갈등이 몸을 갉습니다. 풀고 가세요.",
  W08R:"흐름이 늦어지는 자리. 결과 늦어도 페이스 유지.",
  W10R:"번아웃 직전. 한 짐만이라도 내려놓기.",
  C05R:"슬픔 회복기. 남은 것에 시선을 두세요.",
  C07R:"환상이 정리되는 자리. 한 가지 선택 후 집중.",
  C08R:"떠나야 함을 알면서 못 떠나는 자리. 작은 한 걸음부터.",
  S03R:"상처가 닫히는 자리. 회복 동안에는 무리 금물.",
  S09R:"걱정이 가벼워지는 자리. 사실을 적어 보세요.",
  S10R:"다시 일어서는 자리. 무리하지 말고 한 걸음씩.",
  P04R:"쥐고 있던 손을 푸는 자리. 필요한 곳에 쓰세요.",
  P05R:"회복의 손길이 들어오는 자리. 거절하지 말고 받으세요.",

  // ===== Nanda Special =====
  N01:"본인의 별을 찾는 자리. 본래 가고 싶었던 회복 방향을 떠올리세요.",
  N02:"단호한 자기 보호. 일정 줄여 자기 시간을 확보하세요.",
  N03:"큰 흐름이 등을 미는 자리. 도약 전 컨디션 점검 필수.",
  N04:"표현이 곧 회복. 감정 풀어내기·예술 활동이 약.",
  N05:"천천히 가는 자리. 오래 묵힌 노하우가 빛납니다.",
  N06:"보살핌의 자리. 어른의 조언·전통 식단이 답.",
  N07:"깊은 곳의 답이 있는 자리. 표면 증상보다 근본 원인을 보세요.",
  N08:"긴 호흡의 회복. 한 달, 일 년 단위로 보세요.",
  N09:"헌신 후의 회복. 자신에게 베푸는 시간이 필요합니다.",
  N10:"옛 방식이 답. 어른의 건강법 한 가지를 시도해 보세요."
};

if (typeof module !== "undefined" && module.exports) { module.exports = { CARDS, HEALTH }; }
